### ISSUE TITLE
Exception happened during processing of request from ('127.0.0.1', 51090)

### ISSUE THREAD

**Issue by MarkoLikes** [w4sp-book/w4sp-lab#11]
Can you help me to solve this? 
The problem happened when I push the Setup button once the lab is launched in the browser :(
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 51090)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------

**Comment by w4sp-book** [comment]
Is this a constant thing or was it a one off error?

**Comment by kfb33** [comment]
I get the following error when I click the setup button in the browser.

Exception happened during processing of request from ('127.0.0.1', 35958)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe

Help please

**Comment by mlande5** [comment]
I have the same issue repeatedly.

**Comment by w4sp-book** [comment]
@mlande5, @kfb33, @MarkoLikes  - Definitely a new bug and was able to reproduce it, need to dig into how to fix it. The good news is that it doesn't actually break the lab. It just breaks the first time the lab tries to build the network graph. After you see that error, if you just refresh the browser the lab should be completely functioning.

**Comment by mlande5** [comment]
Apologies for discovering new was hoping that wasn't the case. I really need to get over the fear of programming and start learning.  When I finish bottling the latest brew will jump on and test and see if refresh lab will get me over the hurdle.  
Thank you
Mike
