### ISSUE TITLE
Lab Never Starts

### ISSUE THREAD

**Issue by mlande5** [w4sp-book/w4sp-lab#13]
I've installed the w4sp lab and while the lab pages comes up clicking setup after several hours nothing happens. 
Any suggestions on how to fix the issue?
sudo python w4sp_webapp.py
['which', 'dumpcap']
['getcap', '/usr/bin/dumpcap']
[*] Caps set correctly on dumpcap
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[*] Not enough w4sp/labs images found, building now
/root/Downloads/w4sp-lab-master/images
['docker', 'build', '-t', 'w4sp/labs:base', 'base']
['docker', 'build', '-t', 'w4sp/labs:switch', 'switch']
['docker', 'build', '-t', 'w4sp/labs:vrrpd', 'vrrpd']
['docker', 'build', '-t', 'w4sp/labs:temp', 'temp']
['docker', 'build', '-t', 'w4sp/labs:inet', 'inet']
['docker', 'build', '-t', 'w4sp/labs:elk', 'elk']
['docker', 'build', '-t', 'w4sp/labs:victims', 'victims']
['docker', 'build', '-t', 'w4sp/labs:wireless', 'wireless']
['docker', 'build', '-t', 'w4sp/labs:ftp_tel', 'ftp_tel']
['docker', 'build', '-t', 'w4sp/labs:samba', 'samba']
['docker', 'ps', '-aq', '--filter', 'label=w4sp=true']
['ifconfig', '-a']
['ip', 'link', 'delete', 'docker0:']
['ip', 'link', 'delete', 'eth0:']
RTNETLINK answers: Operation not supported
['ip', 'link', 'delete', 'lo:']
RTNETLINK answers: Operation not supported
['ip', 'netns']
['pkill', 'dhclient']
['ifconfig', '-a']
['service', 'network-manager', 'start']
['service', 'networking', 'restart']
['service', 'docker', 'restart']
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[*] Lab Launched, Starting Browser
[*] Do not close this terminal. Closing Terminal will terminate lab.
127.0.0.1 - - [19/Jul/2017 23:21:51] "GET / HTTP/1.1" 200 -
{'nodes': [{'color': 'rgb(204,0,0)', 'title': u'eth0 : 10.0.2.15 <br>docker0 : 172.17.0.1 <br>', 'id': 1, 'label': ' kali '}], 'edges': []}
127.0.0.1 - - [19/Jul/2017 23:21:54] "GET /getnet HTTP/1.1" 200 -
127.0.0.1 - - [19/Jul/2017 23:21:54] "GET /is_ips HTTP/1.1" 404 -
127.0.0.1 - - [19/Jul/2017 23:21:54] "GET /favicon.ico HTTP/1.1" 404 -
['docker', 'ps', '-aq', '--filter', 'label=w4sp=true']
['ifconfig', '-a']
['ip', 'link', 'delete', 'docker0:']
['ip', 'link', 'delete', 'eth0:']
RTNETLINK answers: Operation not supported
['ip', 'link', 'delete', 'lo:']
RTNETLINK answers: Operation not supported
['ip', 'netns']
['pkill', 'dhclient']
['ifconfig', '-a']
['service', 'network-manager', 'start']
['service', 'networking', 'restart']
['service', 'docker', 'restart']
['docker', 'ps', '-aq', '--filter', 'label=w4sp=true']
['ifconfig', '-a']
['ip', 'link', 'delete', 'docker0:']
['ip', 'link', 'delete', 'eth0:']
RTNETLINK answers: Operation not supported
['ip', 'link', 'delete', 'lo:']
RTNETLINK answers: Operation not supported
['ip', 'netns']
['pkill', 'dhclient']
['ifconfig', '-a']
['service', 'network-manager', 'start']
['service', 'networking', 'restart']
['service', 'docker', 'restart']
['docker', 'run', '-id', '--privileged', '--name', 'sw1', '--hostname', 'sw1', '--net=none', 'w4sp/labs:switch']
['docker', 'inspect', '-f', "'{{.State.Pid}}'", '9a33d582bab8a05d123c4cbe3e8a9728ab86140c13c05a79c413a94a69c4a178']
['ln', '-s', '/proc/10655/ns/net', '/var/run/netns/sw1']
['docker', 'run', '-id', '--privileged', '--name', 'r1', '--hostname', 'r1', '--net=none', 'w4sp/labs:vrrpd']
['docker', 'inspect', '-f', "'{{.State.Pid}}'", 'c460e1dfc9641d14951a65b13b67d64204a2427bee39804d606066b84ad97653']
['ln', '-s', '/proc/10706/ns/net', '/var/run/netns/r1']
['docker', 'run', '-id', '--privileged', '--name', 'r2', '--hostname', 'r2', '--net=none', 'w4sp/labs:vrrpd']
['docker', 'inspect', '-f', "'{{.State.Pid}}'", 'a82b0f11e06bff349afdba12185e383d29e2b1395b1b570ae392ac42eef5b154']
['ln', '-s', '/proc/10768/ns/net', '/var/run/netns/r2']
['docker', 'run', '-id', '--privileged', '--name', 'vic1', '--hostname', 'vic1', '--net=none', 'w4sp/labs:victims']
['docker', 'inspect', '-f', "'{{.State.Pid}}'", '0772076c6b246f10222ea6b3fb08010c682f6e7a655ebd6ced26a372004a2335']
['ln', '-s', '/proc/10858/ns/net', '/var/run/netns/vic1']
['docker', 'run', '-id', '--privileged', '--name', 'smb1', '--hostname', 'smb1', '--net=none', 'w4sp/labs:samba']
['docker', 'inspect', '-f', "'{{.State.Pid}}'", 'a101c024b047315ff762eb09c79bdf7821c60ac15cc730569cfd743f9c3d1d47']
['ln', '-s', '/proc/10978/ns/net', '/var/run/netns/smb1']
['docker', 'run', '-id', '--privileged', '--name', 'ftp1', '--hostname', 'ftp1', '--net=none', 'w4sp/labs:ftp_tel']
['docker', 'inspect', '-f', "'{{.State.Pid}}'", '04374fe3fe223e39aa6d31249f2cb966aef8078075ca7e77a3d1f4126148de23']
['ln', '-s', '/proc/11075/ns/net', '/var/run/netns/ftp1']
['ip', 'link', 'add', 'r1_0', 'type', 'veth', 'peer', 'name', 'tmp']
['ip', 'link', 'set', 'tmp', 'netns', '10655']
['ip', 'link', 'set', 'r1_0', 'netns', '10706']
['ip', 'netns', 'exec', 'sw1', 'ethtool', '-K', 'tmp', 'rx', 'off', 'tx', 'off']
['ip', 'link', 'set', 'dev', 'tmp', 'name', 'r1_0']
['ethtool', '-K', 'r1_0', 'rx', 'off', 'tx', 'off']
['ip', 'link', 'add', 'r2_0', 'type', 'veth', 'peer', 'name', 'tmp']
['ip', 'link', 'set', 'tmp', 'netns', '10655']
['ip', 'link', 'set', 'r2_0', 'netns', '10768']
['ip', 'netns', 'exec', 'sw1', 'ethtool', '-K', 'tmp', 'rx', 'off', 'tx', 'off']
['ip', 'link', 'set', 'dev', 'tmp', 'name', 'r2_0']
['ethtool', '-K', 'r2_0', 'rx', 'off', 'tx', 'off']
['ip', 'link', 'add', 'vic1_0', 'type', 'veth', 'peer', 'name', 'tmp']
['ip', 'link', 'set', 'tmp', 'netns', '10655']
['ip', 'link', 'set', 'vic1_0', 'netns', '10858']
['ip', 'netns', 'exec', 'sw1', 'ethtool', '-K', 'tmp', 'rx', 'off', 'tx', 'off']
['ip', 'link', 'set', 'dev', 'tmp', 'name', 'vic1_0']
['ethtool', '-K', 'vic1_0', 'rx', 'off', 'tx', 'off']
['ip', 'link', 'add', 'smb1_0', 'type', 'veth', 'peer', 'name', 'tmp']
['ip', 'link', 'set', 'tmp', 'netns', '10655']
['ip', 'link', 'set', 'smb1_0', 'netns', '10978']
['ip', 'netns', 'exec', 'sw1', 'ethtool', '-K', 'tmp', 'rx', 'off', 'tx', 'off']
['ip', 'link', 'set', 'dev', 'tmp', 'name', 'smb1_0']
['ethtool', '-K', 'smb1_0', 'rx', 'off', 'tx', 'off']
['ip', 'link', 'add', 'ftp1_0', 'type', 'veth', 'peer', 'name', 'tmp']
['ip', 'link', 'set', 'tmp', 'netns', '10655']
['ip', 'link', 'set', 'ftp1_0', 'netns', '11075']
['ip', 'netns', 'exec', 'sw1', 'ethtool', '-K', 'tmp', 'rx', 'off', 'tx', 'off']
['ip', 'link', 'set', 'dev', 'tmp', 'name', 'ftp1_0']
['ethtool', '-K', 'ftp1_0', 'rx', 'off', 'tx', 'off']
['ip', 'addr', 'add', '192.100.200.96/24', 'dev', 'br0']
['docker', 'run', '-id', '--privileged', '--name', 'sw2', '--hostname', 'sw2', '--net=none', 'w4sp/labs:switch']
['docker', 'inspect', '-f', "'{{.State.Pid}}'", '31866dbdd834d959a71a79aa244e5a4806e626ade8d228178ee2befc6912a641']
['ln', '-s', '/proc/11513/ns/net', '/var/run/netns/sw2']
['docker', 'run', '-id', '--privileged', '--name', 'inet', '--hostname', 'inet', '--net=none', 'w4sp/labs:inet']
['docker', 'inspect', '-f', "'{{.State.Pid}}'", '3066a3edd941e6218bf1c7221755c97bbc1d9f5a95d5f728b9ea08b477aa9643']
['ln', '-s', '/proc/11628/ns/net', '/var/run/netns/inet']
['docker', 'run', '-id', '--privileged', '--name', 'vic4', '--hostname', 'vic4', '--net=none', 'w4sp/labs:victims']
['docker', 'inspect', '-f', "'{{.State.Pid}}'", '50171cba66913f4c3415ad1104ea336af35ef6d409d29d4d64988eb9dcede514']
['ln', '-s', '/proc/11722/ns/net', '/var/run/netns/vic4']
['docker', 'run', '-id', '--privileged', '--name', 'smb2', '--hostname', 'smb2', '--net=none', 'w4sp/labs:samba']
['docker', 'inspect', '-f', "'{{.State.Pid}}'", '446b47e3965d17777e270b0a12d55604d402f8d9f83ac10f80f8b09498cf394b']
['ln', '-s', '/proc/11808/ns/net', '/var/run/netns/smb2']
['docker', 'run', '-id', '--privileged', '--name', 'ftp2', '--hostname', 'ftp2', '--net=none', 'w4sp/labs:ftp_tel']
['docker', 'inspect', '-f', "'{{.State.Pid}}'", 'd77cc79350b1a9293489446d5358d5682726adf43d103a6eec41692e4443a870']
['ln', '-s', '/proc/11898/ns/net', '/var/run/netns/ftp2']
['ip', 'link', 'add', 'r1_1', 'type', 'veth', 'peer', 'name', 'tmp']
['ip', 'link', 'set', 'tmp', 'netns', '11513']
['ip', 'link', 'set', 'r1_1', 'netns', '10706']
['ip', 'netns', 'exec', 'sw2', 'ethtool', '-K', 'tmp', 'rx', 'off', 'tx', 'off']
['ip', 'link', 'set', 'dev', 'tmp', 'name', 'r1_1']
['ethtool', '-K', 'r1_1', 'rx', 'off', 'tx', 'off']
['ip', 'link', 'add', 'r2_1', 'type', 'veth', 'peer', 'name', 'tmp']
['ip', 'link', 'set', 'tmp', 'netns', '11513']
['ip', 'link', 'set', 'r2_1', 'netns', '10768']
['ip', 'netns', 'exec', 'sw2', 'ethtool', '-K', 'tmp', 'rx', 'off', 'tx', 'off']
['ip', 'link', 'set', 'dev', 'tmp', 'name', 'r2_1']
['ethtool', '-K', 'r2_1', 'rx', 'off', 'tx', 'off']
['ip', 'link', 'add', 'inet_0', 'type', 'veth', 'peer', 'name', 'tmp']
['ip', 'link', 'set', 'tmp', 'netns', '11513']
['ip', 'link', 'set', 'inet_0', 'netns', '11628']
['ip', 'netns', 'exec', 'sw2', 'ethtool', '-K', 'tmp', 'rx', 'off', 'tx', 'off']
['ip', 'link', 'set', 'dev', 'tmp', 'name', 'inet_0']
['ethtool', '-K', 'inet_0', 'rx', 'off', 'tx', 'off']
['ip', 'link', 'add', 'vic4_0', 'type', 'veth', 'peer', 'name', 'tmp']
['ip', 'link', 'set', 'tmp', 'netns', '11513']
['ip', 'link', 'set', 'vic4_0', 'netns', '11722']
['ip', 'netns', 'exec', 'sw2', 'ethtool', '-K', 'tmp', 'rx', 'off', 'tx', 'off']
['ip', 'link', 'set', 'dev', 'tmp', 'name', 'vic4_0']
['ethtool', '-K', 'vic4_0', 'rx', 'off', 'tx', 'off']
['ip', 'link', 'add', 'smb2_0', 'type', 'veth', 'peer', 'name', 'tmp']
['ip', 'link', 'set', 'tmp', 'netns', '11513']
['ip', 'link', 'set', 'smb2_0', 'netns', '11808']
['ip', 'netns', 'exec', 'sw2', 'ethtool', '-K', 'tmp', 'rx', 'off', 'tx', 'off']
['ip', 'link', 'set', 'dev', 'tmp', 'name', 'smb2_0']
['ethtool', '-K', 'smb2_0', 'rx', 'off', 'tx', 'off']
['ip', 'link', 'add', 'ftp2_0', 'type', 'veth', 'peer', 'name', 'tmp']
['ip', 'link', 'set', 'tmp', 'netns', '11513']
['ip', 'link', 'set', 'ftp2_0', 'netns', '11898']
['ip', 'netns', 'exec', 'sw2', 'ethtool', '-K', 'tmp', 'rx', 'off', 'tx', 'off']
['ip', 'link', 'set', 'dev', 'tmp', 'name', 'ftp2_0']
['ethtool', '-K', 'ftp2_0', 'rx', 'off', 'tx', 'off']
['ip', 'addr', 'add', '10.100.200.65/24', 'dev', 'br0']
['ip', 'link', 'set', 'eth0', 'down']
['ip', 'link', 'set', 'eth0', 'name', 'root']
['ip', 'link', 'set', 'root', 'netns', 'inet']
['ip', 'link', 'add', 'root_0', 'type', 'veth', 'peer', 'name', 'tmp']
['ip', 'link', 'set', 'tmp', 'netns', '10655']
['ip', 'link', 'set', 'root_0', 'netns', '1']
['ip', 'netns', 'exec', 'sw1', 'ethtool', '-K', 'tmp', 'rx', 'off', 'tx', 'off']
['ip', 'link', 'set', 'dev', 'tmp', 'name', 'root_0']
['ethtool', '-K', 'root_0', 'rx', 'off', 'tx', 'off']
['brctl', 'addif', 'br0', 'root_0']
['ip', 'link', 'set', 'root_0', 'up']
['service', 'network-manager', 'stop']
['ip', 'link', 'set', 'root_0', 'name', 'w4sp_lab']
['dhclient', '-v', 'w4sp_lab']
Internet Systems Consortium DHCP Client 4.3.5
Copyright 2004-2016 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/
Listening on LPF/w4sp_lab/e2:7d:a6:24:8f:39
Sending on   LPF/w4sp_lab/e2:7d:a6:24:8f:39
Sending on   Socket/fallback
DHCPDISCOVER on w4sp_lab to 255.255.255.255 port 67 interval 7
DHCPREQUEST of 192.100.200.113 on w4sp_lab to 255.255.255.255 port 67
DHCPOFFER of 192.100.200.113 from 192.100.200.96
DHCPACK of 192.100.200.113 from 192.100.200.96
smbd.service is not active, cannot reload.
invoke-rc.d: initscript smbd, action "reload" failed.
bound to 192.100.200.113 -- renewal in 1360 seconds.
['route', 'add', '-net', '192.100.200.0', 'netmask', '255.255.255.0', 'gw', '10.100.200.1']
127.0.0.1 - - [19/Jul/2017 23:27:02] "GET /setup HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 40158)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
10655 connected 10706
10655 connected 10768
10655 connected 10858
10655 connected 10978
10655 connected 11075
10706 connected 11513
10768 connected 11513
11513 connected 11628
11513 connected 11722
11513 connected 11808
11513 connected 11898
{'nodes': [{'title': u'br0 : 192.100.200.96 <br>', 'id': '10655', 'label': 'sw1'}, {'title': u'r1_0 : 192.100.200.58 <br>', 'id': '10706', 'label': 'r1'}, {'title': u'r2_0 : 192.100.200.72 <br>', 'id': '10768', 'label': 'r2'}, {'title': u'vic1_0 : 192.100.200.149 <br>', 'id': '10858', 'label': 'vic1'}, {'title': u'smb1_0 : 192.100.200.178 <br>', 'id': '10978', 'label': 'smb1'}, {'title': u'ftp1_0 : 192.100.200.145 <br>', 'id': '11075', 'label': 'ftp1'}, {'title': u'br0 : 10.100.200.65 <br>', 'id': '11513', 'label': 'sw2'}, {'color': 'rgb(0,255,0)', 'title': u'root : 10.0.2.15 <br>inet_0 : 10.100.200.61 <br>', 'id': '11628', 'label': 'inet'}, {'title': u'vic4_0 : 10.100.200.123 <br>', 'id': '11722', 'label': 'vic4'}, {'title': u'smb2_0 : 10.100.200.161 <br>', 'id': '11808', 'label': 'smb2'}, {'title': u'ftp2_0 : 10.100.200.164 <br>', 'id': '11898', 'label': 'ftp2'}, {'color': 'rgb(204,0,0)', 'title': u'docker0 : 172.17.0.1 <br>w4sp_lab : 192.100.200.113 <br>', 'id': 1, 'label': ' kali '}], 'edges': [{'to': '10706', 'from': '10655'}, {'to': '10768', 'from': '10655'}, {'to': '10858', 'from': '10655'}, {'to': '10978', 'from': '10655'}, {'to': '11075', 'from': '10655'}, {'to': '10655', 'from': 1}, {'to': '11513', 'from': '10706'}, {'to': '11513', 'from': '10768'}, {'to': '11628', 'from': '11513'}, {'to': '11722', 'from': '11513'}, {'to': '11808', 'from': '11513'}, {'to': '11898', 'from': '11513'}]}
127.0.0.1 - - [19/Jul/2017 23:27:02] "GET /getnet HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 40160)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
^C
Session terminated, terminating shell...Traceback (most recent call last):
  File "w4sp_webapp.py", line 530, in <module>
    subprocess.call(['su', '-', 'w4sp-lab', '-c', 'firefox 127.0.0.1:5000'])
  File "/usr/lib/python2.7/subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 1073, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/lib/python2.7/subprocess.py", line 121, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
###!!! [Child][MessageChannel] Error: (msgtype=0x3E0003,name=PCompositable::Msg_Destroy) Channel error: cannot send/recv
###!!! [Child][MessageChannel] Error: (msgtype=0x3E0003,name=PCompositable::Msg_Destroy) Channel error: cannot send/recv
###!!! [Child][MessageChannel] Error: (msgtype=0xE20003,name=PTexture::Msg_Destroy) Channel error: cannot send/recv
###!!! [Child][MessageChannel] Error: (msgtype=0xE20003,name=PTexture::Msg_Destroy) Channel error: cannot send/recv
###!!! [Child][MessageChannel] Error: (msgtype=0x3E0003,name=PCompositable::Msg_Destroy) Channel error: cannot send/recv
###!!! [Child][MessageChannel] Error: (msgtype=0xE20003,name=PTexture::Msg_Destroy) Channel error: cannot send/recv
###!!! [Child][MessageChannel] Error: (msgtype=0xE20003,name=PTexture::Msg_Destroy) Channel error: cannot send/recv
###!!! [Child][MessageChannel] Error: (msgtype=0x3E0003,name=PCompositable::Msg_Destroy) Channel error: cannot send/recv
[GFX1-]: Receive IPC close with reason=AbnormalShutdown
[Child 10015] WARNING: pipe error (3): Connection reset by peer: file /build/firefox-esr-XWSZH3/firefox-esr-52.2.0esr/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 322
[Child 10015] ###!!! ABORT: Aborting on channel error.: file /build/firefox-esr-XWSZH3/firefox-esr-52.2.0esr/ipc/glue/MessageChannel.cpp, line 2152
[Child 10015] ###!!! ABORT: Aborting on channel error.: file /build/firefox-esr-XWSZH3/firefox-esr-52.2.0esr/ipc/glue/MessageChannel.cpp, line 2152
w4sp-lab@kali:/root/Downloads/w4sp-lab-master$  ...terminated.

**Comment by w4sp-book** [comment]
hey @mlande5 - responded in the other ticket, but this is definitely an issue, good news is it is just a UI issue, if you refresh the browser after you get the "Broken Pipe" issue then the lab will be fully functional.

**Comment by mlande5** [comment]
Hello 
Ok ran into issue with Docker.   
sudo apt-get update,
sudo apt-get install docker  didn't use docker-ce generates error message that it can't be found. w4
reboot, 
sudo service docker start 
sudo python w4sp_webapp.py 
got an error message that uncaptured task thrown.  
waited a few moments and then refreshed UI and the lab fired up. 
Shut everything down and brought the vm back up login and start the process again.  
w4sp-lab-master$
sudo service docker start 
sudo python w4sp_webapp.py 
I will get the error [Errno32 ] Broken pipe hit refresh the UI and lab comes up.  
But at least I'm in.  
Thank you
Mike

**Comment by w4sp-book** [comment]
@mlande5 thanks for the update, glad it is working, hope to get that UI issue ironed out soon.
