### ISSUE TITLE
Failed to start docker.service

### ISSUE THREAD

**Issue by ceriyeung** [w4sp-book/w4sp-lab#17]
w4sp-lab@kali:/root/Downloads/w4sp-lab-master$ sudo python w4sp_webapp.py
['which', 'dumpcap']
['getcap', '/usr/bin/dumpcap']
[*] Caps set correctly on dumpcap
Get:1 https://apt.dockerproject.org/repo debian-stretch InRelease [48.7 kB]
Err:1 https://apt.dockerproject.org/repo debian-stretch InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F76221572C52609D
Hit:2 http://mirrors.neusoft.edu.cn/kali kali-rolling InRelease
Reading package lists... Done
W: GPG error: https://apt.dockerproject.org/repo debian-stretch InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F76221572C52609D
E: The repository 'https://apt.dockerproject.org/repo debian-stretch InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
apt-transport-https is already the newest version (1.5~rc4).
bridge-utils is already the newest version (1.5-14).
ca-certificates is already the newest version (20170717).
software-properties-common is already the newest version (0.96.20.2-1).
0 upgraded, 0 newly installed, 0 to remove and 1411 not upgraded.
Get:1 https://apt.dockerproject.org/repo debian-stretch InRelease [48.7 kB]
Err:1 https://apt.dockerproject.org/repo debian-stretch InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F76221572C52609D
Hit:2 http://mirrors.neusoft.edu.cn/kali kali-rolling InRelease
Reading package lists... Done
W: GPG error: https://apt.dockerproject.org/repo debian-stretch InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F76221572C52609D
E: The repository 'https://apt.dockerproject.org/repo debian-stretch InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  aufs-dkms aufs-tools cgroupfs-mount dkms linux-compiler-gcc-6-x86 linux-headers-4.12.0-kali2-amd64
  linux-headers-4.12.0-kali2-common linux-headers-amd64 linux-kbuild-4.12
Suggested packages:
  aufs-dev python3-apport
The following NEW packages will be installed:
  aufs-dkms aufs-tools cgroupfs-mount dkms docker-engine linux-compiler-gcc-6-x86
  linux-headers-4.12.0-kali2-amd64 linux-headers-4.12.0-kali2-common linux-headers-amd64 linux-kbuild-4.12
0 upgraded, 10 newly installed, 0 to remove and 1411 not upgraded.
Need to get 31.4 MB of archives.
After this operation, 165 MB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  docker-engine
E: There were unauthenticated packages and -y was used without --allow-unauthenticated
Failed to start docker.service: Unit docker.service not found.
Traceback (most recent call last):
  File "w4sp_webapp.py", line 480, in <module>
    images = subprocess.check_output(['docker', 'images']).split('\n')
  File "/usr/lib/python2.7/subprocess.py", line 212, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
w4sp-lab@kali:/root/Downloads/w4sp-lab-master$

**Comment by ceriyeung** [comment]
Hi, 

Got a error return after the installation.  My Kai is the newest version not sure the problem.  Thanks.
