### ISSUE TITLE
issue on second startup

### ISSUE THREAD

**Issue by MarkHyphen** [w4sp-book/w4sp-lab#18]
Hello.  So, I have a strange issue.  I can get through the install no problem and the lab environment works just fine.  I install, hit setup, refresh the screen and things seems to work find.  However, I then shutdown via the browser GUI and that seems to work.  Something that is odd though is that the terminal fails to return to the prompt.  Thus, I have tried to either hit ctrl-c or just X the terminal out.

Upon reboot or starting the Kali VM the lab will no longer work.  I get the browser GUI but when I hit setup something happens and the button that used to be labeled "setup" becomes "error" and there is nothing I can do about it.  Hitting the error button quickly flashes an error window that pops up and disappears faster than I can read the message and the terminal cycles through some code but there is no way to work the lab.  My only option is to go to the previous VM snapshot that I made prior to installing the lab and reinstall the lab.  Then again, I can use the lab.  If this didn't take 15 minutes each time it wouldn't be that big of a deal but it does and makes things a huge pain.  

Here is the terminal window upon restart of the program when I start getting errors.  Hopefully you can help me out!!!  Thanks.
```
['which', 'dumpcap']
['getcap', '/usr/bin/dumpcap']
[*] Caps set correctly on dumpcap
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[*] Not enough w4sp/labs images found, building now
/root/Downloads/w4sp-lab-master/images
['docker', 'build', '-t', 'w4sp/labs:base', 'base']
['docker', 'build', '-t', 'w4sp/labs:temp', 'temp']
['docker', 'build', '-t', 'w4sp/labs:victims', 'victims']
['docker', 'build', '-t', 'w4sp/labs:samba', 'samba']
['docker', 'build', '-t', 'w4sp/labs:wireless', 'wireless']
['docker', 'build', '-t', 'w4sp/labs:elk', 'elk']
['docker', 'build', '-t', 'w4sp/labs:ftp_tel', 'ftp_tel']
['docker', 'build', '-t', 'w4sp/labs:inet', 'inet']
['docker', 'build', '-t', 'w4sp/labs:switch', 'switch']
['docker', 'build', '-t', 'w4sp/labs:vrrpd', 'vrrpd']
['docker', 'ps', '-aq', '--filter', 'label=w4sp=true']
['ifconfig', '-a']
['ip', 'link', 'delete', 'docker0:']
['ip', 'link', 'delete', 'eth0:']
RTNETLINK answers: Operation not supported
['ip', 'link', 'delete', 'lo:']
RTNETLINK answers: Operation not supported
['ip', 'netns']
['pkill', 'dhclient']
['ifconfig', '-a']
['service', 'network-manager', 'start']
['service', 'networking', 'restart']
['service', 'docker', 'restart']
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[*] Lab Launched, Starting Browser
[*] Do not close this terminal. Closing Terminal will terminate lab.
127.0.0.1 - - [26/Sep/2017 11:04:56] "GET / HTTP/1.1" 200 -
{'nodes': [{'color': 'rgb(204,0,0)', 'title': u'eth0 : 192.168.1.119 <br>docker0 : 172.17.0.1 <br>', 'id': 1, 'label': ' kali '}], 'edges': []}
127.0.0.1 - - [26/Sep/2017 11:04:57] "GET /getnet HTTP/1.1" 200 -
127.0.0.1 - - [26/Sep/2017 11:04:57] "GET /is_ips HTTP/1.1" 404 -
127.0.0.1 - - [26/Sep/2017 11:04:57] "GET /favicon.ico HTTP/1.1" 404 -
['docker', 'ps', '-aq', '--filter', 'label=w4sp=true']
['ifconfig', '-a']
['ip', 'link', 'delete', 'docker0:']
['ip', 'link', 'delete', 'eth0:']
RTNETLINK answers: Operation not supported
['ip', 'link', 'delete', 'lo:']
RTNETLINK answers: Operation not supported
['ip', 'netns']
['pkill', 'dhclient']
['ifconfig', '-a']
['service', 'network-manager', 'start']
['service', 'networking', 'restart']
['service', 'docker', 'restart']
['docker', 'ps', '-aq', '--filter', 'label=w4sp=true']
['ifconfig', '-a']
['ip', 'link', 'delete', 'docker0:']
['ip', 'link', 'delete', 'eth0:']
RTNETLINK answers: Operation not supported
['ip', 'link', 'delete', 'lo:']
RTNETLINK answers: Operation not supported
['ip', 'netns']
['pkill', 'dhclient']
['ifconfig', '-a']
['service', 'network-manager', 'start']
['service', 'networking', 'restart']
['service', 'docker', 'restart']
Job for docker.service failed.
See "systemctl  status docker.service" and "journalctl  -xe" for details.
Traceback (most recent call last):
  File "w4sp_webapp.py", line 163, in setup
    w4sp.setup_network2('eth0')
  File "/root/Downloads/w4sp-lab-master/w4sp.py", line 39, in setup_network2
    docker_clean()
  File "/root/Downloads/w4sp-lab-master/w4sp_app/utils.py", line 148, in docker_clean
    r('service docker restart')
  File "/root/Downloads/w4sp-lab-master/w4sp_app/utils.py", line 83, in r
    return subprocess.check_output(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['service', 'docker', 'restart']' returned non-zero exit status 1

127.0.0.1 - - [26/Sep/2017 11:05:07] "GET /setup HTTP/1.1" 200 -
{'nodes': [{'color': 'rgb(204,0,0)', 'title': u'eth0 : 192.168.1.119 <br>', 'id': 1, 'label': ' kali '}], 'edges': []}
127.0.0.1 - - [26/Sep/2017 11:05:07] "GET /getnet HTTP/1.1" 200 -
127.0.0.1 - - [26/Sep/2017 11:05:08] "GET /is_ips HTTP/1.1" 404 -
['docker', 'ps', '-aq', '--filter', 'label=w4sp=true']
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[*] Did not shutdown cleanly, trying again
['docker', 'ps', '-aq', '--filter', 'label=w4sp=true']
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
['docker', 'ps', '-aq', '--filter', 'label=w4sp=true']
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Traceback (most recent call last):
  File "w4sp_webapp.py", line 163, in setup
    w4sp.setup_network2('eth0')
  File "/root/Downloads/w4sp-lab-master/w4sp.py", line 39, in setup_network2
    docker_clean()
  File "/root/Downloads/w4sp-lab-master/w4sp_app/utils.py", line 114, in docker_clean
    out = r('docker ps -aq --filter label=w4sp=true').split('\n')[:-1]
  File "/root/Downloads/w4sp-lab-master/w4sp_app/utils.py", line 83, in r
    return subprocess.check_output(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['docker', 'ps', '-aq', '--filter', 'label=w4sp=true']' returned non-zero exit status 1

127.0.0.1 - - [26/Sep/2017 11:05:14] "GET /setup HTTP/1.1" 200 -
{'nodes': [{'color': 'rgb(204,0,0)', 'title': u'eth0 : 192.168.1.119 <br>', 'id': 1, 'label': ' kali '}], 'edges': []}
127.0.0.1 - - [26/Sep/2017 11:05:14] "GET /getnet HTTP/1.1" 200 -
127.0.0.1 - - [26/Sep/2017 11:05:14] "GET /is_ips HTTP/1.1" 404 -
['docker', 'ps', '-aq', '--filter', 'label=w4sp=true']
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[*] Did not shutdown cleanly, trying again
['docker', 'ps', '-aq', '--filter', 'label=w4sp=true']
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
['docker', 'ps', '-aq', '--filter', 'label=w4sp=true']
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Traceback (most recent call last):
  File "w4sp_webapp.py", line 163, in setup
    w4sp.setup_network2('eth0')
  File "/root/Downloads/w4sp-lab-master/w4sp.py", line 39, in setup_network2
    docker_clean()
  File "/root/Downloads/w4sp-lab-master/w4sp_app/utils.py", line 114, in docker_clean
    out = r('docker ps -aq --filter label=w4sp=true').split('\n')[:-1]
  File "/root/Downloads/w4sp-lab-master/w4sp_app/utils.py", line 83, in r
    return subprocess.check_output(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['docker', 'ps', '-aq', '--filter', 'label=w4sp=true']' returned non-zero exit status 1

127.0.0.1 - - [26/Sep/2017 11:05:18] "GET /setup HTTP/1.1" 200 -
{'nodes': [{'color': 'rgb(204,0,0)', 'title': u'eth0 : 192.168.1.119 <br>', 'id': 1, 'label': ' kali '}], 'edges': []}
127.0.0.1 - - [26/Sep/2017 11:05:18] "GET /getnet HTTP/1.1" 200 -
127.0.0.1 - - [26/Sep/2017 11:05:18] "GET /is_ips HTTP/1.1" 404 -
```

**Comment by vrechson** [comment]
I'm getting the same error!

**Comment by pmfortunato** [comment]
Me too.  Any sign of help?

**Comment by nkabir** [comment]
Reinstall docker-machine

`$ sudo apt install --reinstall docker-machine`

**Comment by vrechson** [comment]
worked! but the correct is:
`$ sudo apt install --reinstall docker-engine`

**Comment by CollinBeder** [comment]
![building kali environment](https://user-images.githubusercontent.com/35827398/37231903-ebf7b8b4-23ba-11e8-98bf-aee04cda64db.PNG)

I have the same error as above, I tried doing:
`$ sudo apt install --reinstall docker-engine` 
and then when I try to re-run: 
`$ sudo python w4sp_webapp.py` 
it will take me to the web UI but it does not allow me to run "setup".. it just continuously shows the screen shot that I posted above? Does anyone know of a fix for this that will work?

**Comment by freemike74** [comment]
Try to  manually restart docker service (even without reinstall docker-engine):
`sudo systemctl  restart docker.service`
