### ISSUE TITLE
Installing W4SP lab

### ISSUE THREAD

**Issue by Fungster** [w4sp-book/w4sp-lab#2]
Command correction on PG 51.  To get the lab installed make sure you use sudo .

Old command
python w4sp_webapp.py

Correct command 
sudo python w4sp_webapp.py

**Comment by enl10me2** [comment]
Thanks for the tip, I kind of figured that was an issue. Now I get this error. 
![capture](https://cloud.githubusercontent.com/assets/26530671/24127987/39bb86ac-0daf-11e7-9404-84acbcf4be9b.JPG)

**Comment by w4sp-book** [comment]
@Fungster good catch, I have documented the current working installation steps [here](https://github.com/w4sp-book/w4sp-lab/wiki/Lab-Installation). Going to create a better readme and link to it so the most current installation instructions are more readily available.

@enl10me2 I think I know what your issue is, I need to fix up the code that handles the docker install. Can you run the following command:

```shell
w4sp-lab@kali:~$ sudo rm /etc/apt/sources.list
[sudo] password for w4sp-lab: 
w4sp-lab@kali:~$ sudo nano /etc/apt/sources.list
```

This should delete the existing apt source list and create a new one using the nano editor, then copy the following line and right click the terminal and select paste:

`deb http://http.kali.org/kali kali-rolling main non-free contrib`

Then hit `ctrl-x` to save the file, then hit the `y` key to confirm the save and then hit enter to keep the save file as /etc/apt/sources.list

Then try and rerun the lab by running w4sp_webapp.py and let me know if it works for you

```shell
w4sp-lab@kali:/root/Downloads/w4sp-lab-master$ sudo python w4sp_webapp.py

```

**Comment by joshuajga** [comment]
Hello W4SP-LAB!!! I'm trying install your w4sp-lab but It gives me an error. I attached image below:
![error w4sp-lab installation](https://cloud.githubusercontent.com/assets/21307625/24624926/9aa86350-18ad-11e7-9263-0c676127a0fa.png)
As can you see I follow your previous post, I can't continue the book without setting up the lab. I need your help, thank you so much

**Comment by arodriguez4530** [comment]
having same problem

**Comment by w4sp-book** [comment]
hey @arodriguez4530 @joshuajga 

I am pretty sure I know what the issue is but haven't had time to test it just yet but want to see if I can get you guys up and running quick. Can both of you try running the following command:

`sudo apt-get install docker-ce`

Then try running `sudo python w4sp_webapp.py` again?

Should be able to debug and provide a code fix later tomorrow but hoping this will fix your issues for the time being. Don't forget to take a snapshot once you verify the lab is working.

**Comment by joshuajga** [comment]
Hi! again, I tried with the command that you suggested us. I attached below the answer:
![error w4sp-lab installation 2](https://cloud.githubusercontent.com/assets/21307625/24693926/2c028c26-19e0-11e7-9f21-234aef7f83bb.jpg)
I've been looking for other way to installing docker-ce, but I can't found a right repository to download and install it. All of them give me download error. Do you know which one it's working?
Thanks a lot. Regards,

**Comment by w4sp-book** [comment]
@joshuajga 

I tried to debug this and I could not replicate it. The lab installs on a recently update Kali image just  fine. If my spanish is correct the issue seems to be that apt can't find the docker-engine or docker-ce packages. Docker is in the process of changing the name of the package from docker-engine to docker-ce but on my machine the docker-engine package is still available.

I am slightly worried this has something to do with the language not being set to english...but not sure how exactly that would be an issue. Can you let me know what you did differently you did during install including what languages etc. you selected so I can try to replicate this?

Can you run the following and show me the output `cat /etc/apt/sources.list`

Also just to be safe can you run the following `sudo apt-get update && sudo apt-get install docker-engine`

@arodriguez4530 - just curious are you using a non-english install of Kali as well?

**Comment by joshuajga** [comment]
hi again, 
firstly, I would like to answer your questions. 
when I tried cat /etc/apt/souces.list I saw this:
![w4sp-lab_sources](https://cloud.githubusercontent.com/assets/21307625/24729791/2296eb20-1a60-11e7-81aa-5b78b9b3382f.jpg)
When I tried sudo apt-get update && sudo apt-get install docker-engine. I saw this:
Couldn't be located the packet docker-engine.
![error w4sp-lab installation 3](https://cloud.githubusercontent.com/assets/21307625/24729793/22cb5b8a-1a60-11e7-9817-7e1fe4bf2537.jpg)
While I was installing Kali Linux, I left all options by default except the language. I download again all git and file version of w4sp_webapp.py I guess it's the last version.
Other idea?
Thanks a lot for spend your time trying fix my problem.

**Comment by w4sp-book** [comment]
Can you show me the output of `uname -r` ?

The only other thing I can think of is that when you created the virtual machine you didn't select Debian (64-bit) as docker is only supported on x64.

**Comment by BumbleBeeDK** [comment]
Hi, having exact same issue ... have double checked all the above, but still no luck ... and uname -r confirms x64 Debian  ...
![image](https://cloud.githubusercontent.com/assets/26982176/24775795/36c09f7c-1b16-11e7-9598-5954e733a14f.png)

**Comment by BumbleBeeDK** [comment]
Hi, have exact same issue ... have double checked everything ... uname -r confirms x64 Debian ... still no luck loading the Docker ... Did re-install both Docker-ce and Engine ... still no luck ... Sources.list is also ok
![virtualbox_kali_w4sp_06_04_2017_22_15_25](https://cloud.githubusercontent.com/assets/26982176/24775921/b7fb24fe-1b16-11e7-89cc-57c36a907f37.png)

**Comment by BumbleBeeDK** [comment]
oh, by the way, gets the same error when trying to re-install the Docker Engine, as the Spanish guy ... Mine also cannot locate the package ...

**Comment by w4sp-book** [comment]
@BumbleBeeDK actually looks like you are having a slightly different issue, can you show me your sources.list?

**Comment by joshuajga** [comment]
Hi again, 
You were right, the problem was the Kali version. When I executed uname command I saw clear. 
![w4sp-lab fixed](https://cloud.githubusercontent.com/assets/21307625/24778263/f418bd3a-1b29-11e7-8cf1-ae748af5593f.jpg)
I have solved it installing a new virtual machine, but is possible migrate the vm from 32 bits to 64 bits. I will do with I have a little time.  
Thanks  a lot, and I hope be of use for anyone.

**Comment by w4sp-book** [comment]
@joshuajga Awesome, glad you got it working! Going to add to the install wiki to make sure it is clear a 64bit vm is needed.

**Comment by BumbleBeeDK** [comment]
Hi 'Book',

here's the Sources.list 
![screenshootw4spsourceslist](https://cloud.githubusercontent.com/assets/26982176/24789218/e8cee7de-1b69-11e7-80be-5f448d31dd2e.png)

... and the uname +r
![unamr_r](https://cloud.githubusercontent.com/assets/26982176/24789271/21a3da92-1b6a-11e7-9140-373e70d584de.png)

Appreciate your time :-)

Regards, 'Yellow Car'

**Comment by w4sp-book** [comment]
@BumbleBeeDK - weird, your sources are all messed up, it is saying the installer was unable to verify, so something happened during your Kali install. You aren't actually unable to install any packages right now, not just docker. It looks like you used an older Kali iso for installation (which may be part of the problem)?

Try adding the following line to your sources.list
`deb http://http.kali.org/kali kali-rolling main non-free contrib`

and then the following to make sure you are updated:

`sudo apt-get update && sudo apt-get dist-upgrade`

You can also just install from the most recent Kali 64 bit iso:

https://www.kali.org/downloads/

That will definitely solve your problem as I ran through the full install again last night to make sure it is indeed not broken (with and without doing dist-upgrade). The issue is Kali is not a very stable platform, they are constantly changing and updating it and I have no hope in trying to make sure the labs will work on all variations. Because of this the only supported version of Kali is the most recently updated 64 bit version.

**Comment by BumbleBeeDK** [comment]
Hey 'Book',
again, appreciate the effort ... gets an error msg on apt-get update ... "method driver /usr/lib/apt/methods/https could not be found" ... and "is the package apt-transport-https installed?"

... I'll try the re-install of Kali since it is 2.1 and not the latest roll 2.2, so you are properly right ...
However, need my home-Internet line, and not this shitty one in my summerhouse ... will be back in a couple of days with news on how that went ;-)

Thanks again "Yellow Car"

**Comment by BumbleBeeDK** [comment]
Almost done with re-install of Kali 2.2 ... have seen apt conf that I din't see previously, so I now bet its gonna work, as you said ;-)

**Comment by BumbleBeeDK** [comment]
Aaarrrggghhhhh, the Kali re-install failed in the dist-upgrade ... try again Sunday night :-(

**Comment by w4sp-book** [comment]
@BumbleBeeDK might as well give it a try without the dist-upgrade, the lab install should work, since the Kali install is new enough. As long as you got through `sudo apt-get upgrade` I would bet it works.

**Comment by BumbleBeeDK** [comment]
I did ... success ... almost ... it now 'hangs' in building images ... builds the base one, and then nothing else happens ... for like 20/30 min. ...? 

So close now ;-)

**Comment by BumbleBeeDK** [comment]
Finally, with a lot of patience ... shitty ISP equals very slow Inet conn ... but, now it works :-)

Will go on with the labs in the book ;-)

Great book, btw !!!

Thanks again, have fun, and remember ... Defense is doable ...

**Comment by w4sp-book** [comment]
@BumbleBeeDK glad you finally got it working! Was going to warn that the initial building of the images may take a little bit longer on a slower ISP. The good news is you only have to go through that process once. 

Make sure you take a snapshot of your Kali VM now, just in case something breaks in the future you will have a working copy to fall back on.

**Comment by pittfan85** [comment]
I have installed the labs on a couple of different instances of Kali Linux within VirtualBox.  The labs that I have worked through have been great.  That being said, each time I install it, I never see a 'start elk' or a 'start wifi' button.  Am I missing something?  How do I get these buttons to appear?

**Comment by ASHWINK07** [comment]
can anyone fix my problem
it shows like this 

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 gsettings-desktop-schemas : Breaks: mutter (< 3.31.4) but 3.30.2-8 is to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
Traceback (most recent call last):
  File "w4sp_webapp.py", line 9, in <module>
    import w4sp
  File "/home/w4sp-lab/Downloads/w4sp-lab-master/w4sp.py", line 1, in <module>
    from w4sp_app import *
  File "/home/w4sp-lab/Downloads/w4sp-lab-master/w4sp_app/__init__.py", line 1, in <module>
    from w4sp_app.container import container,ns_root,c
  File "/home/w4sp-lab/Downloads/w4sp-lab-master/w4sp_app/container.py", line 22, in <module>
    subprocess.check_call(['apt-get', 'install', 'python3-netifaces'])
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['apt-get', 'install', 'python3-netifaces']' returned non-zero exit status 100

**Comment by giuseppe427** [comment]
salve, ho un problema ad installare w4sp su kali linux . Ho seguito tutte le procedure ma non riesco
