### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by x0rcist** [w4sp-book/w4sp-lab#22]
Hi, 

I am trying to install on latest VM of Kali i.e. 2017.3.  And receiving following error.

any advise ???

---------------------------------------

Fetched 31.3 MB in 1min 25s (365 kB/s)                                         
E: Failed to fetch http://kali.mirror.garr.it/mirrors/kali/pool/main/a/aufs/aufs-dkms_4.13+20171002-1_amd64.deb  Connection failed [IP: 90.147.164.69 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Failed to start docker.service: Unit docker.service not found.
Traceback (most recent call last):
  File "w4sp_webapp.py", line 480, in <module>
    images = subprocess.check_output(['docker', 'images']).split('\n')
  File "/usr/lib/python2.7/subprocess.py", line 212, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by robinkarmakar** [comment]
Getting the same error. Can anyone help with this?

**Comment by guest321** [comment]
What happens when you try  run apt-get update or try with --fix-missing?
I had difficulties so downloaded, updated, upgraded and dist-upgraded kali. Still doesn't work because of some crappy coding errors, but might be worth doing this to at least start with a clean slate.
