### ISSUE TITLE
Lab install error - 404 on web page and docker build failing.

### ISSUE THREAD

**Issue by simple1111** [w4sp-book/w4sp-lab#28]
FALSE ENTRY - SQUID PROXY BLOCKING TRAFFIC - APOLOGIES.

**Comment by simple1111** [comment]
Sorry - unable to attach error and screenshot (something went really wrong, and we can't process that file. Try again). After trying again, same error.

**Comment by simple1111** [comment]
![screenshot_2018-01-22_19-32-34](https://user-images.githubusercontent.com/33653954/35213234-0835d80e-ffb1-11e7-8a46-d014a6fca6a4.png)

**Comment by simple1111** [comment]
ALL INFORMATION AND ERRORS FOR INSTALL
go to https://apt.dockerproject.org/ and download gpg file
apt-add key gpg
apt update apt upgrade -y

Login as w4sp-lab. Run command sudo python "/root/Downloads/w4sp-lab-master/w4sp_webapp.py"

===========================================================================================

ERROR:
[*] Not run from the script directory, changing dirs
['which', 'dumpcap']
['getcap', '/usr/bin/dumpcap']
[*] Caps set correctly on dumpcap
Hit:1 https://apt.dockerproject.org/repo debian-stretch InRelease
Hit:2 http://kali.mirror.garr.it/mirrors/kali kali-rolling InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
apt-transport-https is already the newest version (1.6~alpha6).
bridge-utils is already the newest version (1.5-14).
ca-certificates is already the newest version (20170717).
software-properties-common is already the newest version (0.96.20.2-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Hit:1 https://apt.dockerproject.org/repo debian-stretch InRelease
Hit:2 http://kali.mirror.garr.it/mirrors/kali kali-rolling InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  aufs-dkms aufs-tools cgroupfs-mount dkms libelf-dev linux-compiler-gcc-7-x86 linux-headers-4.14.0-kali3-amd64 linux-headers-4.14.0-kali3-common linux-headers-amd64 linux-kbuild-4.14 zlib1g-dev
Suggested packages:
  aufs-dev python3-apport
The following NEW packages will be installed:
  aufs-dkms aufs-tools cgroupfs-mount dkms docker-engine libelf-dev linux-compiler-gcc-7-x86 linux-headers-4.14.0-kali3-amd64 linux-headers-4.14.0-kali3-common linux-headers-amd64 linux-kbuild-4.14 zlib1g-dev
0 upgraded, 12 newly installed, 0 to remove and 0 not upgraded.
Need to get 31.9 MB of archives.
After this operation, 167 MB of additional disk space will be used.
Get:1 https://apt.dockerproject.org/repo debian-stretch/main amd64 docker-engine amd64 17.05.0~ce-0~debian-stretch [21.7 MB]
Get:2 http://kali.mirror.garr.it/mirrors/kali kali-rolling/main amd64 dkms all 2.3-3 [74.9 kB]                                                                                                                   
Get:3 http://kali.mirror.garr.it/mirrors/kali kali-rolling/main amd64 linux-kbuild-4.14 amd64 4.14.12-2kali2 [739 kB]                                                                                            
Get:4 http://kali.mirror.garr.it/mirrors/kali kali-rolling/main amd64 aufs-dkms amd64 4.14+20171218-1 [179 kB]                                                                                                   
Get:5 http://kali.mirror.garr.it/mirrors/kali kali-rolling/main amd64 aufs-tools amd64 1:4.9+20170918-1 [104 kB]                                                                                                 
Get:6 http://kali.mirror.garr.it/mirrors/kali kali-rolling/main amd64 cgroupfs-mount all 1.4 [6,276 B]                                                                                                           
Get:7 http://kali.mirror.garr.it/mirrors/kali kali-rolling/main amd64 zlib1g-dev amd64 1:1.2.8.dfsg-5 [205 kB]                                                                                                   
Get:8 http://kali.mirror.garr.it/mirrors/kali kali-rolling/main amd64 libelf-dev amd64 0.170-0.2 [71.5 kB]                                                                                                       
Get:9 http://kali.mirror.garr.it/mirrors/kali kali-rolling/main amd64 linux-compiler-gcc-7-x86 amd64 4.14.12-2kali2 [511 kB]                                                                                     
Get:10 http://kali.mirror.garr.it/mirrors/kali kali-rolling/main amd64 linux-headers-4.14.0-kali3-common all 4.14.12-2kali2 [7,841 kB]                                                                           
Get:11 http://kali.mirror.garr.it/mirrors/kali kali-rolling/main amd64 linux-headers-4.14.0-kali3-amd64 amd64 4.14.12-2kali2 [465 kB]                                                                            
Get:12 http://kali.mirror.garr.it/mirrors/kali kali-rolling/main amd64 linux-headers-amd64 amd64 4.14+89+kali1 [6,880 B]                                                                                         
Fetched 31.9 MB in 49s (650 kB/s)                                                                                                                                                                                
Selecting previously unselected package dkms.
(Reading database ... 330646 files and directories currently installed.)
Preparing to unpack .../00-dkms_2.3-3_all.deb ...
Unpacking dkms (2.3-3) ...
Selecting previously unselected package linux-kbuild-4.14.
Preparing to unpack .../01-linux-kbuild-4.14_4.14.12-2kali2_amd64.deb ...
Unpacking linux-kbuild-4.14 (4.14.12-2kali2) ...
Selecting previously unselected package aufs-dkms.
Preparing to unpack .../02-aufs-dkms_4.14+20171218-1_amd64.deb ...
Unpacking aufs-dkms (4.14+20171218-1) ...
Selecting previously unselected package aufs-tools.
Preparing to unpack .../03-aufs-tools_1%3a4.9+20170918-1_amd64.deb ...
Unpacking aufs-tools (1:4.9+20170918-1) ...
Selecting previously unselected package cgroupfs-mount.
Preparing to unpack .../04-cgroupfs-mount_1.4_all.deb ...
Unpacking cgroupfs-mount (1.4) ...
Selecting previously unselected package docker-engine.
Preparing to unpack .../05-docker-engine_17.05.0~ce-0~debian-stretch_amd64.deb ...
Unpacking docker-engine (17.05.0~ce-0~debian-stretch) ...
Selecting previously unselected package zlib1g-dev:amd64.
Preparing to unpack .../06-zlib1g-dev_1%3a1.2.8.dfsg-5_amd64.deb ...
Unpacking zlib1g-dev:amd64 (1:1.2.8.dfsg-5) ...
Selecting previously unselected package libelf-dev:amd64.
Preparing to unpack .../07-libelf-dev_0.170-0.2_amd64.deb ...
Unpacking libelf-dev:amd64 (0.170-0.2) ...
Selecting previously unselected package linux-compiler-gcc-7-x86.
Preparing to unpack .../08-linux-compiler-gcc-7-x86_4.14.12-2kali2_amd64.deb ...
Unpacking linux-compiler-gcc-7-x86 (4.14.12-2kali2) ...
Selecting previously unselected package linux-headers-4.14.0-kali3-common.
Preparing to unpack .../09-linux-headers-4.14.0-kali3-common_4.14.12-2kali2_all.deb ...
Unpacking linux-headers-4.14.0-kali3-common (4.14.12-2kali2) ...
Selecting previously unselected package linux-headers-4.14.0-kali3-amd64.
Preparing to unpack .../10-linux-headers-4.14.0-kali3-amd64_4.14.12-2kali2_amd64.deb ...
Unpacking linux-headers-4.14.0-kali3-amd64 (4.14.12-2kali2) ...
Selecting previously unselected package linux-headers-amd64.
Preparing to unpack .../11-linux-headers-amd64_4.14+89+kali1_amd64.deb ...
Unpacking linux-headers-amd64 (4.14+89+kali1) ...
Setting up aufs-tools (1:4.9+20170918-1) ...
Setting up docker-engine (17.05.0~ce-0~debian-stretch) ...
update-rc.d: We have no instructions for the docker init script.
update-rc.d: It looks like a non-network service, we enable it.
Setting up linux-kbuild-4.14 (4.14.12-2kali2) ...
Setting up cgroupfs-mount (1.4) ...
update-rc.d: We have no instructions for the cgroupfs-mount init script.
update-rc.d: It looks like a non-network service, we enable it.
Setting up dkms (2.3-3) ...
Processing triggers for libc-bin (2.26-4) ...
Processing triggers for systemd (236-3) ...
Processing triggers for man-db (2.7.6.1-4) ...
Setting up linux-compiler-gcc-7-x86 (4.14.12-2kali2) ...
Setting up linux-headers-4.14.0-kali3-common (4.14.12-2kali2) ...
Setting up zlib1g-dev:amd64 (1:1.2.8.dfsg-5) ...
Setting up aufs-dkms (4.14+20171218-1) ...
Loading new aufs-4.14+20171218 DKMS files...
Building for 4.14.0-kali3-amd64
Building initial module for 4.14.0-kali3-amd64
Done.

aufs:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.14.0-kali3-amd64/kernel/fs/aufs/

depmod...

DKMS: install completed.
Setting up libelf-dev:amd64 (0.170-0.2) ...
Setting up linux-headers-4.14.0-kali3-amd64 (4.14.12-2kali2) ...
Setting up linux-headers-amd64 (4.14+89+kali1) ...
[*] Not enough w4sp/labs images found, building now
/root/Downloads/w4sp-lab-master/images
['docker', 'build', '-t', 'w4sp/labs:base', 'base']
Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Traceback (most recent call last):
  File "/root/Downloads/w4sp-lab-master/w4sp_webapp.py", line 499, in <module>
    w4sp.docker_build('images/')
  File "/root/Downloads/w4sp-lab-master/w4sp_app/utils.py", line 95, in docker_build
    r('docker build -t w4sp/labs:base base')
  File "/root/Downloads/w4sp-lab-master/w4sp_app/utils.py", line 83, in r
    return subprocess.check_output(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['docker', 'build', '-t', 'w4sp/labs:base', 'base']' returned non-zero exit status 1

===========================================================================================

ERROR2:
[*] Not run from the script directory, changing dirs
['which', 'dumpcap']
['getcap', '/usr/bin/dumpcap']
[*] Caps set correctly on dumpcap
[*] Not enough w4sp/labs images found, building now
/root/Downloads/w4sp-lab-master/images
['docker', 'build', '-t', 'w4sp/labs:base', 'base']
Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Traceback (most recent call last):
  File "/root/Downloads/w4sp-lab-master/w4sp_webapp.py", line 499, in <module>
    w4sp.docker_build('images/')
  File "/root/Downloads/w4sp-lab-master/w4sp_app/utils.py", line 95, in docker_build
    r('docker build -t w4sp/labs:base base')
  File "/root/Downloads/w4sp-lab-master/w4sp_app/utils.py", line 83, in r
    return subprocess.check_output(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['docker', 'build', '-t', 'w4sp/labs:base', 'base']' returned non-zero exit status 1

===========================================================================================

RAN: sudo systemctl reset-failed docker

ERROR3:
[*] Not run from the script directory, changing dirs
['which', 'dumpcap']
['getcap', '/usr/bin/dumpcap']
[*] Caps set correctly on dumpcap
[*] Not enough w4sp/labs images found, building now
/root/Downloads/w4sp-lab-master/images
['docker', 'build', '-t', 'w4sp/labs:base', 'base']
Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Traceback (most recent call last):
  File "/root/Downloads/w4sp-lab-master/w4sp_webapp.py", line 499, in <module>
    w4sp.docker_build('images/')
  File "/root/Downloads/w4sp-lab-master/w4sp_app/utils.py", line 95, in docker_build
    r('docker build -t w4sp/labs:base base')
  File "/root/Downloads/w4sp-lab-master/w4sp_app/utils.py", line 83, in r
    return subprocess.check_output(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['docker', 'build', '-t', 'w4sp/labs:base', 'base']' returned non-zero exit status 1
