### ISSUE TITLE
I got an error with setting up the lab

### ISSUE THREAD

**Issue by q4f21** [w4sp-book/w4sp-lab#31]
Not sure whats going on but I received a really long error. There was more to it but I'm just posting the end part. I hope someone is able to help me with this. Thank you in advance.

Exception happened during processing of request from ('127.0.0.1', 56852)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
5436 connected 5489
5436 connected 5538
5436 connected 5603
5436 connected 5671
5436 connected 5750
5489 connected 6130
5538 connected 6130
6130 connected 6193
6130 connected 6254
6130 connected 6319
6130 connected 6387
{'nodes': [{'title': u'br0 : 192.100.200.62 <br>', 'id': '5436', 'label': 'sw1'}, {'title': u'r1_0 : 192.100.200.40 <br>', 'id': '5489', 'label': 'r1'}, {'title': u'r2_0 : 192.100.200.74 <br>', 'id': '5538', 'label': 'r2'}, {'title': u'vic1_0 : 192.100.200.198 <br>', 'id': '5603', 'label': 'vic1'}, {'title': u'smb1_0 : 192.100.200.108 <br>', 'id': '5671', 'label': 'smb1'}, {'title': u'ftp1_0 : 192.100.200.130 <br>', 'id': '5750', 'label': 'ftp1'}, {'title': u'br0 : 10.100.200.61 <br>', 'id': '6130', 'label': 'sw2'}, {'color': 'rgb(0,255,0)', 'title': u'root : 192.168.0.198 <br>inet_0 : 10.100.200.54 <br>', 'id': '6193', 'label': 'inet'}, {'title': u'vic4_0 : 10.100.200.111 <br>', 'id': '6254', 'label': 'vic4'}, {'title': u'smb2_0 : 10.100.200.128 <br>', 'id': '6319', 'label': 'smb2'}, {'title': u'ftp2_0 : 10.100.200.179 <br>', 'id': '6387', 'label': 'ftp2'}, {'color': 'rgb(204,0,0)', 'title': u'docker0 : 172.17.0.1 <br>w4sp_lab : 192.100.200.200 <br>', 'id': 1, 'label': ' kali '}], 'edges': [{'to': '5489', 'from': '5436'}, {'to': '5538', 'from': '5436'}, {'to': '5603', 'from': '5436'}, {'to': '5671', 'from': '5436'}, {'to': '5750', 'from': '5436'}, {'to': '5436', 'from': 1}, {'to': '6130', 'from': '5489'}, {'to': '6130', 'from': '5538'}, {'to': '6193', 'from': '6130'}, {'to': '6254', 'from': '6130'}, {'to': '6319', 'from': '6130'}, {'to': '6387', 'from': '6130'}]}
127.0.0.1 - - [14/Feb/2018 16:49:36] "GET /getnet HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 56854)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------

**Comment by Linux-Viking** [comment]
Did you try refreshing your browser?
