### ISSUE TITLE
Lab Install Help Requested (sorry I'm n00b at this!)

### ISSUE THREAD

**Issue by TheLoneMango** [w4sp-book/w4sp-lab#39]
Thanks so much for this lab and the book!  ;-)
On the lab install, I am getting this error.  (see below)
I'm reading the book and I really want this lab to work! 

P.S.  I read through the other errors, but didn't see this one.  Apologies if I missed it.  

Begin Error Text***************************************************

[*] Not enough w4sp/labs images found, building now
/home/w4sp-lab/Downloads/w4sp-lab-master/images
['docker', 'build', '-t', 'w4sp/labs:base', 'base']
['docker', 'build', '-t', 'w4sp/labs:temp', 'temp']
['docker', 'build', '-t', 'w4sp/labs:vrrpd', 'vrrpd']
['docker', 'build', '-t', 'w4sp/labs:samba', 'samba']
['docker', 'build', '-t', 'w4sp/labs:victims', 'victims']
['docker', 'build', '-t', 'w4sp/labs:switch', 'switch']
The command '/bin/sh -c apt-get install -y suricata logstash openjdk-7-jre-headless' returned a non-zero code: 100
Traceback (most recent call last):
  File "w4sp_webapp.py", line 499, in <module>
    w4sp.docker_build('images/')
  File "/home/w4sp-lab/Downloads/w4sp-lab-master/w4sp_app/utils.py", line 102, in docker_build
    r('docker build -t $image_name $image')
  File "/home/w4sp-lab/Downloads/w4sp-lab-master/w4sp_app/utils.py", line 83, in r
    return subprocess.check_output(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['docker', 'build', '-t', 'w4sp/labs:switch', 'switch']' returned non-zero exit status 100

**Comment by Nelson556** [comment]
TheLoneMango did you solve this error

**Comment by jalex1-ops** [comment]
@Nelson556 hey, i am having the same issue. Could you help resolve it?
