### ISSUE TITLE
w4sp_webapp execute Error!

### ISSUE THREAD

**Issue by Parkgunny** [w4sp-book/w4sp-lab#45]
w4sp-lab@kali:~/Downloads/w4sp-lab-master$ sudo python w4sp_webapp.py 
['which', 'dumpcap']
Traceback (most recent call last):
  File "w4sp_webapp.py", line 441, in <module>
    w4sp.check_dumpcap()
  File "/home/w4sp-lab/Downloads/w4sp-lab-master/w4sp_app/utils.py", line 13, in check_dumpcap
    dumpcap = r('which dumpcap').strip()
  File "/home/w4sp-lab/Downloads/w4sp-lab-master/w4sp_app/utils.py", line 83, in r
    return subprocess.check_output(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['which', 'dumpcap']' returned non-zero exit status 1

I don't execute w4sp_webap.py 
what should I do?

**Comment by Tini1993** [comment]
I got the same error.

**Comment by Tini1993** [comment]
Solved.
The problem was that I was using the light version of Kali Linux, which doesn't come with wireshark.
So either install it manually (sudo apt-get install wireshark) or get Kali's full version.

Now on to the next error.
