### ISSUE TITLE
error installing w4sp-lab

### ISSUE THREAD

**Issue by giopoi** [w4sp-book/w4sp-lab#48]
E: Impossibile impostare il blocco /var/lib/dpkg/lock-frontend - open (11: Risorsa temporaneamente non disponibile)
E: Impossibile acquisire il blocco sul frontend dpkg (/var/lib/dpkg/lock-frontend). Un altro processo potrebbe tenerlo occupato.
Failed to start docker.service: Unit docker.service not found.
Traceback (most recent call last):
  File "w4sp_webapp.py", line 480, in <module>
    images = subprocess.check_output(['docker', 'images']).split('\n')
  File "/usr/lib/python2.7/subprocess.py", line 216, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by bluejosem** [comment]
Translating, if anyone finds mistakes fix:
It's impossible to set up the block  /var/lib/dpkg/lock-frontend - open (11: Resource temporarily not available)
It's impossible to acquire the block whose frontend dpkg (/var/lib/dpkg/lock-frontend). Another process might have it occupied.
Failed to start docker.service: Unit docker.service not found.
Traceback (most recent call last):
File "w4sp_webapp.py", line 480, in 
images = subprocess.check_output(['docker', 'images']).split('\n')
File "/usr/lib/python2.7/subprocess.py", line 216, in check_output
process = Popen(stdout=PIPE, *popenargs, **kwargs)
File "/usr/lib/python2.7/subprocess.py", line 394, in init
errread, errwrite)
File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
raise child_exception
OSError: [Errno 2] No such file or directory
