### ISSUE TITLE
installing w4sp-lab new error

### ISSUE THREAD

**Issue by giopoi** [w4sp-book/w4sp-lab#49]
Il pacchetto "docker-engine" non ha candidati da installare
Failed to start docker.service: Unit docker.service not found.
Traceback (most recent call last):
  File "w4sp_webapp.py", line 480, in <module>
    images = subprocess.check_output(['docker', 'images']).split('\n')
  File "/usr/lib/python2.7/subprocess.py", line 216, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
w4sp-lab@kali:~/Downloads/w4sp-lab-master$

**Comment by mikeybro** [comment]
Is anyone trying to fix this broken lab?? I still can't get it to run , error, after error after error

**Comment by eamantovani** [comment]
try the kali version 2017.4 amd64, with that the istallation works fine
ciao
andrea
