### ISSUE TITLE
W4SP-Lab installation error

### ISSUE THREAD

**Issue by gesumbo** [w4sp-book/w4sp-lab#55]
I'm trying to install the lab, but I got this error, even though I've done everything is said in the wiki guide:

[*] Not enough w4sp/labs images found, building now
/home/w4sp-lab/Downloads/w4sp-lab-master/images
['docker', 'build', '-t', 'w4sp/labs:base', 'base']
The command '/bin/sh -c apt-get -y update && apt-get -y upgrade' returned a non-zero code: 100
Traceback (most recent call last):
  File "w4sp_webapp.py", line 499, in <module>
    w4sp.docker_build('images/')
  File "/home/w4sp-lab/Downloads/w4sp-lab-master/w4sp_app/utils.py", line 95, in docker_build
    r('docker build -t w4sp/labs:base base')
  File "/home/w4sp-lab/Downloads/w4sp-lab-master/w4sp_app/utils.py", line 83, in r
    return subprocess.check_output(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['docker', 'build', '-t', 'w4sp/labs:base', 'base']' returned non-zero exit status 100

Can anyone help please?
Thanks a lot

**Comment by dq82elo** [comment]
Hi, i have some problem. I launch command: sudo python w4sp_webapp.py and the terminal says this: 
Lettura elenco dei pacchetti... Fatto
Generazione albero delle dipendenze       
Lettura informazioni sullo stato... Fatto
E: Impossibile trovare il pacchetto python-netifaces
Traceback (most recent call last):
  File "w4sp_webapp.py", line 8, in <module>
    import w4sp
  File "/home/w4sp-lab/Scaricati/w4sp-lab-master/w4sp.py", line 1, in <module>
    from w4sp_app import *
  File "/home/w4sp-lab/Scaricati/w4sp-lab-master/w4sp_app/__init__.py", line 1, in <module>
    from container import container,ns_root,c
  File "/home/w4sp-lab/Scaricati/w4sp-lab-master/w4sp_app/container.py", line 22, in <module>
    subprocess.check_call(['apt-get', 'install', 'python-netifaces'])
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['apt-get', 'install', 'python-netifaces']' returned non-zero exit status 100

my system is (with uname -a command) :
Linux kali 5.6.0-kali1-amd64 #1 SMP Debian 5.6.7-1kali1 (2020-05-12) x86_64 GNU/Linux

sources.list  is:

deb http://http.kali.org/kali kali-rolling main non-free contrib

what's the problem? Thank you!
