### ISSUE TITLE
error: impossibile trovare 'python-netifaces'

### ISSUE THREAD

**Issue by giovanni-it** [w4sp-book/w4sp-lab#63]
When I type the command ' sudo python w4sp_webapp.py ' , it interrupted. Below, there is screenshot (in italian language):
root@w4sp:/home/w4sp-lab/Scaricati/w4sp-lab-master# python w4sp_webapp.py
Lettura elenco dei pacchetti... Fatto
Generazione albero delle dipendenze       
Lettura informazioni sullo stato... Fatto
E: Impossibile trovare il pacchetto python-netifaces
Traceback (most recent call last):
  File "w4sp_webapp.py", line 8, in <module>
    import w4sp
  File "/home/w4sp-lab/Scaricati/w4sp-lab-master/w4sp.py", line 1, in <module>
    from w4sp_app import *
  File "/home/w4sp-lab/Scaricati/w4sp-lab-master/w4sp_app/__init__.py", line 1, in <module>
    from container import container,ns_root,c
  File "/home/w4sp-lab/Scaricati/w4sp-lab-master/w4sp_app/container.py", line 22, in <module>
    subprocess.check_call(['apt-get', 'install', 'python-netifaces'])
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['apt-get', 'install', 'python-netifaces']' returned non-zero exit status 100

 After I tried to install python-netifaces but without success. 
root@w4sp:/home/w4sp-lab/Scaricati/w4sp-lab-master# apt-get install python-netifaces
Lettura elenco dei pacchetti... Fatto                                                                       
Generazione albero delle dipendenze                                                                         
Lettura informazioni sullo stato... Fatto                                                                   
E: Impossibile trovare il pacchetto python-netifaces .

Help me: thanks

**Comment by giacomomangelli** [comment]
italiano per italiano, devi applicare le correzioni che ha inserito l'autore, stanno nella sezione "pull requests" dentro file "changes". le devi applicare a mano una per una, dopodichè seguire le istruzioni poichè devi usare la python3.
Comunque non ti basterà a farlo partire, personalmente sto correggendo un altro paio di errori, uno in particolare che non permette la connessione al pid del processo, poichè lo copia in malo modo portandosi dietro caratteri aggiuntivi.
spero di averti aiutato.
saluti

**Comment by giovanni-it** [comment]
Grazie per avermi risposto. Sto facendo diversi tentativi, che spero risolvano. Ti aggiornerò, grazie ancora.
Saluti

**Comment by giacomomangelli** [comment]
niente, spero che hai capito le correzioni dove sono

**Comment by giacomomangelli** [comment]
nel frattempo ti aggiorno io dicendoti che sono riuscito con successo a farlo partire

**Comment by giovanni-it** [comment]
Ti allego i file di log che abbiamo ottenuto con un mio amico dopo aver fatto le correzioni suggerite. Stiamo studiando un po di python3 per orientarci un pò nel codice
[log-1.txt](https://github.com/w4sp-book/w4sp-lab/files/4622858/log-1.txt)
[log-2.txt](https://github.com/w4sp-book/w4sp-lab/files/4622859/log-2.txt)
Ci puoi dare qualche dritta?
Grazie

**Comment by giacomomangelli** [comment]
si sono gli ultimi errori che ho corretto, mo cerco di fare l'upload del file, comunque sia puoi farli da te:
sono da aggiungere una b davanti a suricata, qui 
```
  File "w4sp_webapp.py", line 213, in is_ips
    if psef('suricata'):
```
per farlo diventare:

`if psef(b'suricata')`

invece l'altro:

```
File "/home/w4sp-lab/Scrivania/w4sp-lab-master/w4sp_app/container.py", line 228, in __init__
    self.mnt_fd = open(self.proc_path + 'mnt')
```

io l'ho risolto facendo una decode dei byte in stringa, ho aggiunto

`self.pid = self.pid.decode("utf-8")`

alla linea prima per permettere la concatenazione

**Comment by giovanni-it** [comment]
Grazie per averci risposto:pomeriggio proviamo e ti aggiorniamo:

**Comment by giovanni-it** [comment]
Caro Meliodas123
ti scrivo per dirti che io e il mio amico Massimo (che è in gambissima rispetto a me) con le tue indicazioni abbiamo risolto e il laboratorio ci funziona: resta solo un problemino su una variabile DISPLAY (tu l'hai avuto? mi piacerebbe sapere come l'hai risolto). Massimo sta preparando un lavoro, che pensiamo possa essere gradito alla comunità. Sta preparando una guida di installazione del w4sp-lab su ubuntu (versioni lts 18.04 e 20.04) dove risolve anche il problema della variabile DISPLAY (a cui si lega il fatto -se ho capito bene- che al doppio clik su una MV, non si aggancia l'avvio di wireshark). Grazie ancora, perchè senza il tuo aiuto, quasi sicuramente avremmo lasciato perdere (volevamo una soluzione chiavi in mano per fare prove sulle reti, no una cosa con una procedura di installazione così impegnativa). Controlla nei prossimi giorni i post: così ci confrontiamo.

**Comment by giacomomangelli** [comment]
ciao, mi fa piacere che siete riusciti a farlo funzionare. L'errore lo ho anche io, ma non me ne sono curato ad essere sincero, poichè funziona anche con quello. Se ti interessa sapere se è legato alla macchina virtuale o meno posso provarlo su kali che ho su partizione fisica, fammi sapere. Per il resto penso sia un buon lavoro quello che state facendo, anche se vi suggerisco di lavorare con kali per una questione di studio. Buon lavoro in ogni caso!

**Comment by Fabiuss81** [comment]
ciao, ho letto la vostra conversazioni e seguito le indicazioni che avete dato. nonostante ciò ho un problema che non riesco a risolvere. quando avvio il setup del lab rimane in loop e non va a termine ... capita anche a voi? come avete risolti??

**Comment by giovanni-it** [comment]
Fabius, 
come ho detto a Meliodas123, stiamo lavorando per preparare una semplice guida per installare il laboratorio. 
Ubuntu 18.04 è l'ambiente in cui tutto sembra funzionare perfettamente -esattamente come descritto nel testo di Bullock e Parker) senza dare problemi  (in Kali2020 e Ubuntu 20.04 funziona pure ma...).
Devi pazientare: prima vorremmo fare un test realizzando un avvelenamento della ARP cache come descritto nel capitolo 5 del libro. Per l'intanto, mi pare che hai aggiustato i file come indicato da jaubin e Meliodas123: prova a tenere sul monitor entrambe le schermate: quella di firefox e quella del terminale. Quando sul terminale sono create le macchine virtuali e il prompt è bloccato su una riga che inizia con 127.0.0.1......., allora fai il refresh della pagina web: può darsi che questo risolva.

**Comment by giovanni-it** [comment]
Caro Meliodas123
Come promesso, dopo alcune sperimentazioni e verifiche, ecco la guida: mi sembra che tutto funzioni bene e crea tutte le macchine virtuali previste nel libro, fino a 'sploit'. Vorrei che gli dai un'occhiata e -se lo ritieni opportuno- crei un nuovo issue (del tipo 'installare w4sp-lab su Ubuntu'). Sotto ti riporto il testo della guida, in allegato la cartella w4sp-lab-master zippata e con tutte le correzioni fatte. Ovviamente vorrei che nel lavoro citassi il mio amico e collega Massimo che dietro le quinte ha fatto 80% di quanto è stato aggiunto da noi al lavoro tuo e di jaubin.
0.0) modificare i sorgenti secondo quanto indicato nella sezione "Pull requests" alla voce "Files changed" 
     (vedi all'indirizzo https://github.com/w4sp-book/w4sp-lab/pull/62 dove 
     c'è link a          https://github.com/w4sp-book/w4sp-lab/pull/62/files/236526aab008403bff72376c187a021a4227e595
     con tutte le modifiche ai sorgenti proposte da jaubin e Meliodas123)


0.1) (ulteriori modifiche indicate da Meliodas123: i numeri di riga fanno riferimento sempre ai files originali, prima delle modifiche indicate al punto 0.0) 
     in "w4sp_webapp.py",  (sezione is_ips)
     
     MODIFICARE:
     line 212     -if psef('suricata')
                  +if psef(b'suricata')

     IN MERITO ALL'ERRORE SOTTOSTANTE, EFFETTUARE LE SEGUENTI MODIFICHE
     e  in "/home/w4sp-lab/Scrivania/w4sp-lab-master/w4sp_app/container.py", (sezione _init_) (la riga 228 era già stata corretta nel punto 0.0)
     PRIMA:
     line 227     -self.proc_path = '/proc/%s/ns/' % self.pid    
     line 228     -self.mnt_fd = open(self.proc_path + 'mnt')  
     
     nella linea precedente inserire nuova riga
     DOPO:
     line 227     +self.pid = self.pid.decode("utf-8")
     line 229     +self.proc_path = '/proc/%s/ns/' % self.pid
     line 230     +self.mnt_fd = open(self.proc_path + 'mnt')

0.2) installare Ubuntu 18.04.4 LTS (va bene anche la versione minimale)

1)   aprire il file /etc/default/grub e modificare 
     riga 11   -GRUB_CMDLINE_LINUX=""
               +GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0"

     quindi digitare il comando
                                $ sudo update-grub2
     e RIAVVIARE

2)   $ sudo apt update && sudo apt dist-upgrade

3)   MODIFCARE FILE w4sp_webappp.py

     riga 29    -subprocess.check_call(['pip', 'install', 'flask'])
                +subprocess.check_call(['pip3', 'install', 'flask'])

     riga 33    -subprocess.check_call(['apt-get', 'install', 'python-flask'])
                +subprocess.check_call(['apt-get', 'install', 'python3-flask'])

     riga 124
     - data['nodes'].append({'id' : 1, 'label' : ' kali ', 'color' : 'rgb(204,0,0)', 'title' : tmp_popup})
     + data['nodes'].append({'id' : 1, 'label' : ' ubuntu ', 'color' : 'rgb(204,0,0)', 'title' : tmp_popup})
                
                                
4)   $ sudo apt install wireshark net-tools  ethtool xterm (autorizzare gli altri utenti a catturare i pacchetti in wireshark)

5)   $ sudo python3 w4sp_webapp.py

6)   $ sudo usermod -aG wireshark w4sp-lab

7)   $ sudo passwd w4sp-lab 

8)   PASSARE ALL’ACCOUNT  w4sp-lab

9)   COPIARE LA DIRECTORY w4sp-lab-master (utilizzata finora) sul desktop dell'utente w4sp-lab e posizionarsi al suo interno ed eseguire:

10)  $ sudo python3 w4sp_webapp.py (verranno costruite una serie di 'MMVV' containerizzate e lanciato in automatico il browser firefox all'indirizzo 127.0.0.1:5000  

11)  INTERROMPERE lo script ion python3 ed eseguire il comando:
     $ sudo usermod -aG docker w4sp-lab
     $ sudo systemctl enable --now docker

12)  successivamente si può procedere all'installazione di metasploit (da amministratore)

12.1)apt install curl (quando richiesto: Y)
12.2)Dalla pagina principale 
                          https://github.com/rapid7/metasploit-framework, 
     navigando si accede all'altra 
                          https://github.com/rapid7/metasploit-framework/wiki/Nightly-Installers 
     e -in base al proprio S.O.- si recupera la riga di istruzione per l'installazione (riporto quella che si è usata)

         curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall && \
         chmod 755 msfinstall && \
         ./msfinstall

12.3. Dopo l'installazione, inserire il comando  'msfconsole'  (per lanciare metasploit)
      e al prompt di metasploit digitare i seguenti comandi:
         msf5 > db_status
         msf5 > search fileformat

NOTA- La procedura vale anche per Kali Linux 2020 (senza bisogno di installare preliminarmente python3-docker) e Ubuntu 20.04. Ma al click sui singoli nodi del 
laboratorio virtuale si avvia solo xterm e per avviare anche wireshark, basta digitare da terminale 'wireshark' (se necessario basta un altro doppio click sul nodo per avere un altro terminale).


[w4sp-lab-master.zip](https://github.com/w4sp-book/w4sp-lab/files/4668619/w4sp-lab-master.zip)
[w4sp-lab-master.zip](https://github.com/w4sp-book/w4sp-lab/files/4668629/w4sp-lab-master.zip)

**Comment by rokigithub** [comment]
ti ringrazio .. sembra tutto ok ... i miei complimenti !!

**Comment by giacomomangelli** [comment]
> 
> 
> Caro Meliodas123
> Come promesso, dopo alcune sperimentazioni e verifiche, ecco la guida: mi sembra che tutto funzioni bene e crea tutte le macchine virtuali previste nel libro, fino a 'sploit'. Vorrei che gli dai un'occhiata e -se lo ritieni opportuno- crei un nuovo issue (del tipo 'installare w4sp-lab su Ubuntu'). Sotto ti riporto il testo della guida, in allegato la cartella w4sp-lab-master zippata e con tutte le correzioni fatte. Ovviamente vorrei che nel lavoro citassi il mio amico e collega Massimo che dietro le quinte ha fatto 80% di quanto è stato aggiunto da noi al lavoro tuo e di jaubin.
> 0.0) modificare i sorgenti secondo quanto indicato nella sezione "Pull requests" alla voce "Files changed"
> (vedi all'indirizzo #62 dove
> c'è link a https://github.com/w4sp-book/w4sp-lab/pull/62/files/236526aab008403bff72376c187a021a4227e595
> con tutte le modifiche ai sorgenti proposte da jaubin e Meliodas123)
> 
> 0.1) (ulteriori modifiche indicate da Meliodas123: i numeri di riga fanno riferimento sempre ai files originali, prima delle modifiche indicate al punto 0.0)
> in "w4sp_webapp.py", (sezione is_ips)
> 
> ```
>  MODIFICARE:
>  line 212     -if psef('suricata')
>               +if psef(b'suricata')
> 
>  IN MERITO ALL'ERRORE SOTTOSTANTE, EFFETTUARE LE SEGUENTI MODIFICHE
>  e  in "/home/w4sp-lab/Scrivania/w4sp-lab-master/w4sp_app/container.py", (sezione _init_) (la riga 228 era già stata corretta nel punto 0.0)
>  PRIMA:
>  line 227     -self.proc_path = '/proc/%s/ns/' % self.pid    
>  line 228     -self.mnt_fd = open(self.proc_path + 'mnt')  
>  
>  nella linea precedente inserire nuova riga
>  DOPO:
>  line 227     +self.pid = self.pid.decode("utf-8")
>  line 229     +self.proc_path = '/proc/%s/ns/' % self.pid
>  line 230     +self.mnt_fd = open(self.proc_path + 'mnt')
> ```
> 
> 0.2) installare Ubuntu 18.04.4 LTS (va bene anche la versione minimale)
> 
>     1. aprire il file /etc/default/grub e modificare
>        riga 11   -GRUB_CMDLINE_LINUX=""
>        +GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0"
>        quindi digitare il comando
>        $ sudo update-grub2
>        e RIAVVIARE
> 
>     2. $ sudo apt update && sudo apt dist-upgrade
> 
>     3. MODIFCARE FILE w4sp_webappp.py
>        riga 29    -subprocess.check_call(['pip', 'install', 'flask'])
>        +subprocess.check_call(['pip3', 'install', 'flask'])
>        riga 33    -subprocess.check_call(['apt-get', 'install', 'python-flask'])
>        +subprocess.check_call(['apt-get', 'install', 'python3-flask'])
>        riga 124
>        
>        * data['nodes'].append({'id' : 1, 'label' : ' kali ', 'color' : 'rgb(204,0,0)', 'title' : tmp_popup})
>        
>        
>        * data['nodes'].append({'id' : 1, 'label' : ' ubuntu ', 'color' : 'rgb(204,0,0)', 'title' : tmp_popup})
> 
>     4. $ sudo apt install wireshark net-tools  ethtool xterm (autorizzare gli altri utenti a catturare i pacchetti in wireshark)
> 
>     5. $ sudo python3 w4sp_webapp.py
> 
>     6. $ sudo usermod -aG wireshark w4sp-lab
> 
>     7. $ sudo passwd w4sp-lab
> 
>     8. PASSARE ALL’ACCOUNT  w4sp-lab
> 
>     9. COPIARE LA DIRECTORY w4sp-lab-master (utilizzata finora) sul desktop dell'utente w4sp-lab e posizionarsi al suo interno ed eseguire:
> 
>     10. $ sudo python3 w4sp_webapp.py (verranno costruite una serie di 'MMVV' containerizzate e lanciato in automatico il browser firefox all'indirizzo 127.0.0.1:5000
> 
>     11. INTERROMPERE lo script ion python3 ed eseguire il comando:
>         $ sudo usermod -aG docker w4sp-lab
>         $ sudo systemctl enable --now docker
> 
>     12. successivamente si può procedere all'installazione di metasploit (da amministratore)
> 
> 
> 12.1)apt install curl (quando richiesto: Y)
> 12.2)Dalla pagina principale
> https://github.com/rapid7/metasploit-framework,
> navigando si accede all'altra
> https://github.com/rapid7/metasploit-framework/wiki/Nightly-Installers
> e -in base al proprio S.O.- si recupera la riga di istruzione per l'installazione (riporto quella che si è usata)
> 
> ```
>      curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall && \
>      chmod 755 msfinstall && \
>      ./msfinstall
> ```
> 
> 12.3. Dopo l'installazione, inserire il comando 'msfconsole' (per lanciare metasploit)
> e al prompt di metasploit digitare i seguenti comandi:
> msf5 > db_status
> msf5 > search fileformat
> 
> NOTA- La procedura vale anche per Kali Linux 2020 (senza bisogno di installare preliminarmente python3-docker) e Ubuntu 20.04. Ma al click sui singoli nodi del
> laboratorio virtuale si avvia solo xterm e per avviare anche wireshark, basta digitare da terminale 'wireshark' (se necessario basta un altro doppio click sul nodo per avere un altro terminale).
> 
> [w4sp-lab-master.zip](https://github.com/w4sp-book/w4sp-lab/files/4668619/w4sp-lab-master.zip)
> [w4sp-lab-master.zip](https://github.com/w4sp-book/w4sp-lab/files/4668629/w4sp-lab-master.zip)

buongiorno, mi complimento innanzi tutto del lavoro ottimo che avete fatto. Proprio per quello penso che sia più corretto se pubblicaste voi questa vostra soluzione, visto che sia io che jaubin (probabilmente) siamo dei semplici lettori che si sono aiutati per poter andare avanti nel libro, visto che l'autore ufficiale ha deciso di non rispondere ai vari issues. Del resto il vostro lavoro sicuramente verrà apprezzato, magari fate una pull request o una merge request e vedete cosa vi dicono! Al massimo se vi va citate voi me, non il contrario, il grosso del lavoro lo avete fatto voi!

**Comment by giovanni-it** [comment]
Caro Meliodas123
ti ringrazio per avermi risposto. Gli impegni di lavoro mi hanno impedito di accedere in questi giorni a questo forum e ti sto rispondendo in ritardo. Ci tenevo alla tua opinione e perciò mi sono fermato e non ho fatto ulteriori passi. Appena mi sarà possibile, farò una traduzione della guida in inglese e -come mi consigli tu- la pubblicherò con una nuova pull request (io e Massimo). Teniamoci in contatto: per il momento ciao e grazie ancora

**Comment by mazzchri** [comment]
salve ragazzi potete aiutarmi non riesco a installare il laboratorio
 
w4sp-lab@4mn3s14:~$ sudo apt install -y python3-docker
[sudo] password di w4sp-lab: 
Lettura elenco dei pacchetti... Fatto
Generazione albero delle dipendenze       
Lettura informazioni sullo stato... Fatto
python3-docker è già alla versione più recente (4.1.0-1.2).
I seguenti pacchetti sono stati installati automaticamente e non sono più richiesti:
  libre2-7 libx265-179 linux-image-5.5.0-kali2-amd64
Usare "sudo apt autoremove" per rimuoverli.
0 aggiornati, 0 installati, 0 da rimuovere e 0 non aggiornati.
w4sp-lab@4mn3s14:~$ sudo python3 w4sp_webapp.py
python3: can't open file 'w4sp_webapp.py': [Errno 2] No such file or directory
w4sp-lab@4mn3s14:~$ cd Scaricati
w4sp-lab@4mn3s14:~/Scaricati$ ls
w4sp-lab-master  w4sp-lab-master.zip
w4sp-lab@4mn3s14:~/Scaricati$ cd w4sp-lab-master
w4sp-lab@4mn3s14:~/Scaricati/w4sp-lab-master$ sudo python3 w4sp_webapp.py
  File "w4sp_webapp.py", line 148
    print ns.pid
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(ns.pid)?

**Comment by giacomomangelli** [comment]
le correzioni sono tutte presenti su pull request e quelle mancanti nei primi post di questa pagina

**Comment by mazzchri** [comment]
il problema e che non saprei come applicarle... ma ci provo ugualmente!!!!!!!!!!!!!!!cominciando dal pull request

**Comment by sh4rk0r** [comment]
buonasera a tutti sto cercando di far funzionare il laboratorio ma ahimè non riesco spero possiate darmi una mano. Sto provando la guida di giovanni-it e meliodas-1234 ma quando mi trovo a dare il comando sudo python3 w3sp_webapp.py sia su ubuntu che su kali mi viene restituito questo messaggio

`RTNETLINK answers: Operation not supported

['ip', 'link', 'delete', b'lo:']
RTNETLINK answers: Operation not supported
['ip', 'netns']
['pkill', 'dhclient']
['ifconfig', '-a']
['service', 'network-manager', 'start']
Failed to start network-manager.service: Unit network-manager.service not found.
Traceback (most recent call last):
  File "w4sp_webapp.py", line 521, in <module>
    w4sp.docker_clean()
  File "/home/w4sp-lab/Desktop/w4sp-lab-master/w4sp_app/utils.py", line 146, in docker_clean
    r('service network-manager start')
  File "/home/w4sp-lab/Desktop/w4sp-lab-master/w4sp_app/utils.py", line 83, in r
    return subprocess.check_output(cmd)
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['service', 'network-manager', 'start']' returned non-zero exit status 5.` 

Ho cercato qualcosa in giro ma non sono riuscito a trovare niente che mi possa aiutare. 
Grazie anticipatamente

**Comment by Chu-Meh** [comment]
i have this same problem. can someone refer me to the appropriate changes by the authors?
