### ISSUE TITLE
Traceback errors on 5.6.0-kali2-amd64 when trying to install.

### ISSUE THREAD

**Issue by metamonsta** [w4sp-book/w4sp-lab#68]
New issue after manually making the changes mentioned in the pull request. Attempting install on 5.6.0-kali2-amd64. 

Traceback (most recent call last):
  File "w4sp_webapp.py", line 9, in <module>
    import w4sp
  File "/opt/w4sp-lab/w4sp.py", line 1, in <module>
    from w4sp_app import *
  File "/opt/w4sp-lab/w4sp_app/__init__.py", line 1, in <module>
    from w4sp_app.container import container,ns_root,c
  File "/opt/w4sp-lab/w4sp_app/container.py", line 68
    ret = libc.setns(ns_fd.fileno(), 0)
                                      ^
IndentationError: unindent does not match any outer indentation level

Please advise,

**Comment by giacomomangelli** [comment]
it looks like you didn't all the changes that are on the pull request, cause the import are written still with the python 2.7 format

**Comment by metamonsta** [comment]
ah, ok. will go back and check again.

**Comment by giacomomangelli** [comment]
anyway it won't work even if you do all the correct change, we discussed the last changes to do in this topic 
error: impossibile trovare 'python-netifaces'
i'm sorry that all the discussion is in italian, i hope you'll find the answer you need

**Comment by metamonsta** [comment]
Thank you Meliodas123! I used the modified master (w4sp-lab-master.zip) that was attached to the following thread: https://github.com/w4sp-book/w4sp-lab/issues/63

I wrote over my existing install with the modified files and I am currently going through the install. So far things are looking like it may be successful. 

Thanks in advance all!
