### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by Breydson** [w4sp-book/w4sp-lab#76]
Need help

I'm trying to install the w4sp-lab but this is giving me this error.

Traceback (most recent call last):
   File "/home/whitehat/Downloads/w4sp-lab-master/w4sp_webapp.py", line 8, in <module>
     import w4sp
   File "/home/whitehat/Downloads/w4sp-lab-master/w4sp.py", line 23
     print r ('ls -sail / root')
           ^
SyntaxError: invalid syntax
------------------------------------------------------
Please how do I solve it?

**Comment by BuhuanJin** [comment]
print (r'ls -sail / root')
