### ISSUE TITLE
Still having problems 

### ISSUE THREAD

**Issue by vincententen** [w4sp-book/w4sp-lab#77]
Although I've applied all the changes in the code, the lab page still not opening. This is what I see on the terminal when I digit: 
sudo python3 w4sp-webapp.py

['which', 'dumpcap']
['getcap', b'/usr/bin/dumpcap']
[*] Error, capabilities not set correctly on dumpcap, setting capabilities
['setcap', '-r', b'/usr/bin/dumpcap']
[*] Not enough w4sp/labs images found, building now
/home/w4sp-lab/Scaricati/w4sp-lab-master/images
['docker', 'build', '-t', 'w4sp/labs:base', 'base']
['docker', 'build', '-t', 'w4sp/labs:vrrpd', 'vrrpd']
['docker', 'build', '-t', 'w4sp/labs:switch', 'switch']
['docker', 'build', '-t', 'w4sp/labs:inet', 'inet']
['docker', 'build', '-t', 'w4sp/labs:samba', 'samba']
['docker', 'build', '-t', 'w4sp/labs:elk', 'elk']
['docker', 'build', '-t', 'w4sp/labs:temp', 'temp']
['docker', 'build', '-t', 'w4sp/labs:ftp_tel', 'ftp_tel']
['docker', 'build', '-t', 'w4sp/labs:victims', 'victims']
['docker', 'build', '-t', 'w4sp/labs:wireless', 'wireless']
['docker', 'ps', '-aq', '--filter', 'label=w4sp=true']
['ifconfig', '-a']
['ip', 'link', 'delete', b'eth0:']
RTNETLINK answers: Operation not supported
['ip', 'link', 'delete', b'lo:']
RTNETLINK answers: Operation not supported
['ip', 'netns']
['pkill', 'dhclient']
['ifconfig', '-a']
['service', 'network-manager', 'start']
Failed to start network-manager.service: Unit network-manager.service not found.
Traceback (most recent call last):
  File "/home/w4sp-lab/Scaricati/w4sp-lab-master/w4sp_webapp.py", line 521, in <module>
    w4sp.docker_clean()
  File "/home/w4sp-lab/Scaricati/w4sp-lab-master/w4sp_app/utils.py", line 146, in docker_clean
    r('service network-manager start')
  File "/home/w4sp-lab/Scaricati/w4sp-lab-master/w4sp_app/utils.py", line 83, in r
    return subprocess.check_output(cmd)
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['service', 'network-manager', 'start']' returned non-zero exit status 5.

please help.

**Comment by Grigorii-Voroshnin** [comment]
https://github.com/Grigorii-Voroshnin/w4sp-lab.git
