### ISSUE TITLE
The command '/bin/sh -c pip install netifaces' returned a non-zero code: 1

### ISSUE THREAD

**Issue by anto-pro** [w4sp-book/w4sp-lab#78]
Hi,

Even after reading and applying the changes mentioned in #62 and #63(more precisely, https://github.com/w4sp-book/w4sp-lab/issues/63#issuecomment-628151640), I'm still not able to set up the lab.

I'm currently using Kali 2020.3. I've been spending the past 3 days trying to fix it, it's quite frustrating because the book is useless without the lab working out. @w4sp-book are please you able to help?

This is what's going on

oot@kali2020:/home/w4sp-lab/Downloads/w4sp-lab-master-final# python3 w4sp_webapp.py
['which', 'dumpcap']
['getcap', b'/usr/bin/dumpcap']
[*] Caps set correctly on dumpcap
[*] Not enough w4sp/labs images found, building now
/home/w4sp-lab/Downloads/w4sp-lab-master-final/images
['docker', 'build', '-t', 'w4sp/labs:base', 'base']
The command '/bin/sh -c pip install netifaces' returned a non-zero code: 1
Traceback (most recent call last):
  File "/home/w4sp-lab/Downloads/w4sp-lab-master-final/w4sp_webapp.py", line 500, in <module>
    w4sp.docker_build('images/')
  File "/home/w4sp-lab/Downloads/w4sp-lab-master-final/w4sp_app/utils.py", line 95, in docker_build
    r('docker build -t w4sp/labs:base base')
  File "/home/w4sp-lab/Downloads/w4sp-lab-master-final/w4sp_app/utils.py", line 83, in r
    return subprocess.check_output(cmd)
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker', 'build', '-t', 'w4sp/labs:base', 'base']' returned non-zero exit status 1.

sorry for the tag, but maybe you have some ideas?
@jaubin @giacomoangeli @giovanni-it

**Comment by harshadrai1961** [comment]
Hi
I have been trying to install the labs in Kali 2020 and it has been very frustrating. Especially for users like me who are not familiar with Linux. I would like to set up my own labs in Virtualbox and would appreciate if you could me some idea of what machines are involved and their configuration so that I can establish my own labs. Thanks so much

**Comment by abcchad** [comment]
Any luck on figuring out the "The command '/bin/sh -c pip install netifaces' returned a non-zero code: 1" error?

**Comment by anto-pro** [comment]
No luck @abcchad, it's sad to see how the authors gave up on this project

**Comment by ghcjsnb** [comment]
So did you fix it?

**Comment by proce95** [comment]
No I didn't

**Comment by anto-pro** [comment]
No I didn't

**Comment by anwarpiracha** [comment]
I have been trying to install it for last 2 days and now stuck at the above error too.  Does any body have the solution for this issue otherwise this book is useless
