### ISSUE TITLE
Code Errors

### ISSUE THREAD

**Issue by rewasp1973** [w4sp-book/w4sp-lab#81]
Hello everyone!

When I run the code, I have these errors:

``Traceback (most recent call last):
  File "/home/w4sp-lab/Scaricati/w4sp-lab-master/w4sp_webapp.py", line 8, in <module>
    import w4sp
  File "/home/w4sp-lab/Scaricati/w4sp-lab-master/w4sp.py", line 1, in <module>
    from w4sp_app import *
  File "/home/w4sp-lab/Scaricati/w4sp-lab-master/w4sp_app/__init__.py", line 1, in <module>
    from container import container,ns_root,c
ModuleNotFoundError: No module named 'container'

Can you help me?

Thank you in advance

**Comment by fajllo** [comment]
Hi,

I have the same error, did you maybe manage to resolve it?

**Comment by 662323** [comment]
go to pull request and check out what jaubin said that may solve your problem

**Comment by 662323** [comment]
if that doesnt work rm all the file and follow this article step by step
this worked for me : https://medium.com/@vaibjav2raj/setting-up-the-w4sp-lab-in-2020-d4df6a3d2a5e

**Comment by Vertux** [comment]
> go to pull request and check out what jaubin said that may solve your problem

It does not solve the issue to install `python3-docker` as recommened in @jaubin pull request.

My Kali version: 

> Linux w4sp 5.19.0-kali2-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.19.11-1kali2 (2022-10-10) x86_64 GNU/Linux


@rewasp1973 Would you please give your issue a more informative description as "Code errors" - thank you.
