### ISSUE TITLE
Trying to get the lab installed and running, having docker build error...need help

### ISSUE THREAD

**Issue by abcchad** [w4sp-book/w4sp-lab#83]
Running Kali 2022.4 (I've tried several other versions, I've gotten further with this one), python 3.10, and the updated w4sp-lab package. I am getting most of the way through the setup and then seems to have a docker error. Does anyone know how to fix this issue? See logs below:
[*] Not enough w4sp/labs images found, building now
/home/w4sp-lab/Downloads/w4sp-lab-master/images
['docker', 'build', '-t', 'w4sp/labs:base', 'base']
The command '/bin/sh -c pip install netifaces' returned a non-zero code: 1
Traceback (most recent call last):
  File "/home/w4sp-lab/Downloads/w4sp-lab-master/w4sp_webapp.py", line 500, in <module>
    w4sp.docker_build('images/')
  File "/home/w4sp-lab/Downloads/w4sp-lab-master/w4sp_app/utils.py", line 95, in docker_build
    r('docker build -t w4sp/labs:base base')
  File "/home/w4sp-lab/Downloads/w4sp-lab-master/w4sp_app/utils.py", line 83, in r
    return subprocess.check_output(cmd)
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker', 'build', '-t', 'w4sp/labs:base', 'base']' returned non-zero exit status 1.

**Comment by ghcjsnb** [comment]
I made the same mistake. Solved it,? bro

**Comment by jumabar** [comment]
You need to edit DockerFile, and install dpkg netifilters into docker.

**Comment by ShirleyCorleone** [comment]
Hi,i've got the same issue,too.BTW,I running Kali the same as yours,whitch mean 2022/4.Here is some error logs below:


['which', 'dumpcap']
['getcap', b'/usr/bin/dumpcap']
[*] Error, capabilities not set correctly on dumpcap, setting capabilities
['setcap', '-r', b'/usr/bin/dumpcap']
[*] Not enough w4sp/labs images found, building now
/home/w4sp-lab/Downloads/w4sp-lab-master/images
['docker', 'build', '-t', 'w4sp/labs:base', 'base']
The command '/bin/sh -c apt-get -y install bridge-utils ethtool' returned a non-zero code: 100
Traceback (most recent call last):
  File "/home/w4sp-lab/Downloads/w4sp-lab-master/w4sp_webapp.py", line 499, in <module>
    w4sp.docker_build('images/')
  File "/home/w4sp-lab/Downloads/w4sp-lab-master/w4sp_app/utils.py", line 95, in docker_build
    r('docker build -t w4sp/labs:base base')
  File "/home/w4sp-lab/Downloads/w4sp-lab-master/w4sp_app/utils.py", line 83, in r
    return subprocess.check_output(cmd)
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker', 'build', '-t', 'w4sp/labs:base', 'base']' returned non-zero exit status 100.

What should I do? If you've solved it ,could you please tell me ?

**Comment by whatsreal** [comment]
I can solve @abcchad 's problem.  The file in w4sp-lab/images/base/DockerFile comment out line #27 that says `RUN pip install netifaces` After that manually install netifaces2 with:

`pip install netifaces2` in the commandline.  I did it both as the regular user and as root (sudo) to be safe.  Then we get past that issue! (I still have a couple others to solve, but forward progress is good!)
