### ISSUE TITLE
[It works!] Setting up the w4sp-lab in 2022

### ISSUE THREAD

**Issue by Huang2077** [w4sp-book/w4sp-lab#85]
Hi guys! I  solved various problems that arose during the installation. Please check the https://medium.com/@huangjingtao2077/setting-up-the-w4sp-lab-in-2022-a3be14241d87
Follow the steps, you can get a new w4sp-lab

**Comment by slowdodo** [comment]
https://github.com/slowdodo/w4sp-lab

**Comment by daptim** [comment]
Hello all, After following this tutorial I could install the lab successfully but when I loaded the lab in the browser the Switch and other nodes connected together loaded separately and Kali itself was standalone. Anyone with suggestions on how to fix this will be appreciated.

**Comment by thepaperrose** [comment]
Did everything in the article and reran w4sp_webapp.py but still getting errors. I'm not worth much when it comes to code, but I'll take a look if I get the chance.

`w4sp-lab㉿kali)-[~/Downloads/w4sp-lab-main]
└─$ sudo python w4sp_webapp.py
['which', 'dumpcap']
['getcap', b'/usr/bin/dumpcap']
[*] Error, capabilities not set correctly on dumpcap, setting capabilities
['setcap', '-r', b'/usr/bin/dumpcap']
[*] Not enough w4sp/labs images found, building now
/home/w4sp-lab/Downloads/w4sp-lab-main/images
['docker', 'build', '-t', 'w4sp/labs:base', 'base']
['docker', 'build', '-t', 'w4sp/labs:switch', 'switch']
['docker', 'build', '-t', 'w4sp/labs:temp', 'temp']
['docker', 'build', '-t', 'w4sp/labs:victims', 'victims']
The command '/bin/sh -c cd scapy && python setup.py install' returned a non-zero code: 1
Traceback (most recent call last):
  File "/home/w4sp-lab/Downloads/w4sp-lab-main/w4sp_webapp.py", line 500, in <module>
    w4sp.docker_build('images/')
  File "/home/w4sp-lab/Downloads/w4sp-lab-main/w4sp_app/utils.py", line 102, in docker_build
    r('docker build -t $image_name $image')
  File "/home/w4sp-lab/Downloads/w4sp-lab-main/w4sp_app/utils.py", line 83, in r
    return subprocess.check_output(cmd)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker', 'build', '-t', 'w4sp/labs:victims', 'victims']' returned non-zero exit status 1.
`
