### ISSUE TITLE
on kali2022 How work?

### ISSUE THREAD

**Issue by shixiangbupt** [w4sp-book/w4sp-lab#86]
on kali2022   ,It  is  python 3.10,  w4sp-lab  does  not  run!

**Comment by shixiangbupt** [comment]
![image](https://user-images.githubusercontent.com/5387481/210922397-c3d00306-42ca-4bc5-8f54-e0e3ca569c01.png)

**Comment by slowdodo** [comment]
https://github.com/w4sp-book/w4sp-lab/issues/87

**Comment by POCCOPOCCO89** [comment]
I have the same problem

**Comment by antrenor** [comment]
I followed all the instructions, even modifying the code as described but it doesn't work.
Ver. Python 3.11.7


Traceback (most recent call last):
  File "/home/antrenor/Downloads/w4sp-lab-master/w4sp_webapp.py", line 9, in <module>
    import w4sp
  File "/home/antrenor/Downloads/w4sp-lab-master/w4sp.py", line 1, in <module>
    from w4sp_app import *
  File "/home/antrenor/Downloads/w4sp-lab-master/w4sp_app/__init__.py", line 1, in <module>
    from w4sp_app.container import container,ns_root,c
  File "/home/antrenor/Downloads/w4sp-lab-master/w4sp_app/container.py", line 1, in <module>
    from w4sp_app.utils import r, docker_clean
  File "/home/antrenor/Downloads/w4sp-lab-master/w4sp_app/utils.py", line 137
    for nic in r('ifconfig -a').split(b'\n\n')[:-1]:
                                                    ^
IndentationError: unindent does not match any outer indentation level
