### ISSUE TITLE
Problemi con codici w4sp_webapp.py 

### ISSUE THREAD

**Issue by Mikael2807** [w4sp-book/w4sp-lab#90]
Salve a tutti,
Ho comprato un libro sull'utilizzo di wireshark e mi ha fatto creare un utente su kali linux per poterci installare il laboratorio w4sp-lab.
Ma quando lancio il comando python w4sp_webapp.py mi vengono fuori molti errori nei codici.
Ho provato a modificare i file seguendo ogni contributo dato dai vostri commenti ma continuo a non riuscirci.
Gli ultimi commenti su come aggiustare lo script risalgono al 2020 e penso che nel mentre sia cambiato qualcosa che impedisce, a quelle correzioni di farmi andare avanti.
Aiutatemi perfavore.
Grazie a tutti
@w4sp-book @w4sp-lab

**Comment by avalenteAvo** [comment]
Ciao,
Confermo anche io la stessa cosa. Quando lancio il comando linux python w4sp_webapp.py vengono fuori in fase di compilazione errori su errori. Non so come procedere onestamente. 

Hello,
I confirm the same thing. When I launch linux command python w4sp_webapp.py arise during compilation many Syntax Errors. At the end the python file is not working. 
Please let me know if you fix these problems.
Thank you

![pytonErrors](https://github.com/w4sp-book/w4sp-lab/assets/104693583/ca97ea60-6476-4aed-9af2-4aeaca7c41d4)

**Comment by pdichiaro78** [comment]
Same problem!! I think this book must be retired form shops! 
It's useless

**Comment by ecd534** [comment]
Same problem!! 
Solution it's here.
https://medium.com/@vaibjav2raj/setting-up-the-w4sp-lab-in-2020-d4df6a3d2a5e

**Comment by SimonBlancoE** [comment]
This problem has been reported years ago, how hasn't it been resolved?

**Comment by SimonBlancoE** [comment]
> Same problem!! Solution it's here. https://medium.com/@vaibjav2raj/setting-up-the-w4sp-lab-in-2020-d4df6a3d2a5e

Solution doesn't work, it throws ot another error:
```

The command '/bin/sh -c pip install netifaces' returned a non-zero code: 1
Traceback (most recent call last):
  File "/home/w4sp-lab/w4sp-lab-master/w4sp_webapp.py", line 500, in <module>
    w4sp.docker_build('images/')
  File "/home/w4sp-lab/w4sp-lab-master/w4sp_app/utils.py", line 95, in docker_build
    r('docker build -t w4sp/labs:base base')
  File "/home/w4sp-lab/w4sp-lab-master/w4sp_app/utils.py", line 83, in r
    return subprocess.check_output(cmd)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker', 'build', '-t', 'w4sp/labs:base', 'base']' returned non-zero exit status 1.

```

**Comment by antrenor** [comment]
Qualcuno ha la soluzione? Ho provato quanto sopra ma nulla help!!
