### ISSUE TITLE
> Same problem!! Solution it's here. https://medium.com/@vaibjav2raj/setting-up-the-w4sp-lab-in-2020-d4df6a3d2a5e

### ISSUE THREAD

**Issue by antrenor** [w4sp-book/w4sp-lab#91]
> Same problem!! Solution it's here. https://medium.com/@vaibjav2raj/setting-up-the-w4sp-lab-in-2020-d4df6a3d2a5e

Solution doesn't work, it throws ot another error:
```

The command '/bin/sh -c pip install netifaces' returned a non-zero code: 1
Traceback (most recent call last):
  File "/home/w4sp-lab/w4sp-lab-master/w4sp_webapp.py", line 500, in <module>
    w4sp.docker_build('images/')
  File "/home/w4sp-lab/w4sp-lab-master/w4sp_app/utils.py", line 95, in docker_build
    r('docker build -t w4sp/labs:base base')
  File "/home/w4sp-lab/w4sp-lab-master/w4sp_app/utils.py", line 83, in r
    return subprocess.check_output(cmd)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker', 'build', '-t', 'w4sp/labs:base', 'base']' returned non-zero exit status 1.

```

_Originally posted by @SimonBlancoE in https://github.com/w4sp-book/w4sp-lab/issues/90#issuecomment-1866583831_
            

I also have the same problem after the various changes to your files. Does anyone have any solution?

**Comment by yoke88** [comment]
check  https://github.com/yoke88/w4sp-lab , you may change the Dockerfile of the base image,  i have changed the default apt repo  which are archive.ubuntu.com and  security.ubuntu.com to mirrors.ustc.edu.cn
